// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package meta

import (
	"time"

	pkgmeta "github.com/choysum-dev/choysum/pkg/meta"
)

// LockLease provides a DB-agnostic mutual exclusion primitive (table meta_lock_lease).
// Acquire/Renew/Release logic lives in internal/state/lease.
//
// Resource should be globally unique (uniqueIndex) to represent one lock.
// ExpiresAt enables lease semantics to recover from crashed owners.
// OwnerId is an opaque identifier generated by the caller.
type LockLease struct {
	pkgmeta.BaseModel `gorm:"embedded"`
	Resource          string `gorm:"uniqueIndex"`
	OwnerId           string
	ExpiresAt         time.Time `gorm:"index"`
}

func (l *LockLease) TableName() string {
	return "meta_lock_lease"
}
