// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: tip.proto

package tippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TipHub_SubscribeThread_FullMethodName        = "/choysum.realtime.v1.TipHub/SubscribeThread"
	TipHub_SubscribeNotifications_FullMethodName = "/choysum.realtime.v1.TipHub/SubscribeNotifications"
)

// TipHubClient is the client API for TipHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TipHubClient interface {
	SubscribeThread(ctx context.Context, in *SubscribeThreadReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tip], error)
	SubscribeNotifications(ctx context.Context, in *SubscribeNotificationsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tip], error)
}

type tipHubClient struct {
	cc grpc.ClientConnInterface
}

func NewTipHubClient(cc grpc.ClientConnInterface) TipHubClient {
	return &tipHubClient{cc}
}

func (c *tipHubClient) SubscribeThread(ctx context.Context, in *SubscribeThreadReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tip], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TipHub_ServiceDesc.Streams[0], TipHub_SubscribeThread_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeThreadReq, Tip]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TipHub_SubscribeThreadClient = grpc.ServerStreamingClient[Tip]

func (c *tipHubClient) SubscribeNotifications(ctx context.Context, in *SubscribeNotificationsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tip], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TipHub_ServiceDesc.Streams[1], TipHub_SubscribeNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeNotificationsReq, Tip]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TipHub_SubscribeNotificationsClient = grpc.ServerStreamingClient[Tip]

// TipHubServer is the server API for TipHub service.
// All implementations must embed UnimplementedTipHubServer
// for forward compatibility.
type TipHubServer interface {
	SubscribeThread(*SubscribeThreadReq, grpc.ServerStreamingServer[Tip]) error
	SubscribeNotifications(*SubscribeNotificationsReq, grpc.ServerStreamingServer[Tip]) error
	mustEmbedUnimplementedTipHubServer()
}

// UnimplementedTipHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTipHubServer struct{}

func (UnimplementedTipHubServer) SubscribeThread(*SubscribeThreadReq, grpc.ServerStreamingServer[Tip]) error {
	return status.Error(codes.Unimplemented, "method SubscribeThread not implemented")
}
func (UnimplementedTipHubServer) SubscribeNotifications(*SubscribeNotificationsReq, grpc.ServerStreamingServer[Tip]) error {
	return status.Error(codes.Unimplemented, "method SubscribeNotifications not implemented")
}
func (UnimplementedTipHubServer) mustEmbedUnimplementedTipHubServer() {}
func (UnimplementedTipHubServer) testEmbeddedByValue()                {}

// UnsafeTipHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TipHubServer will
// result in compilation errors.
type UnsafeTipHubServer interface {
	mustEmbedUnimplementedTipHubServer()
}

func RegisterTipHubServer(s grpc.ServiceRegistrar, srv TipHubServer) {
	// If the following call panics, it indicates UnimplementedTipHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TipHub_ServiceDesc, srv)
}

func _TipHub_SubscribeThread_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeThreadReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TipHubServer).SubscribeThread(m, &grpc.GenericServerStream[SubscribeThreadReq, Tip]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TipHub_SubscribeThreadServer = grpc.ServerStreamingServer[Tip]

func _TipHub_SubscribeNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeNotificationsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TipHubServer).SubscribeNotifications(m, &grpc.GenericServerStream[SubscribeNotificationsReq, Tip]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TipHub_SubscribeNotificationsServer = grpc.ServerStreamingServer[Tip]

// TipHub_ServiceDesc is the grpc.ServiceDesc for TipHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TipHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "choysum.realtime.v1.TipHub",
	HandlerType: (*TipHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeThread",
			Handler:       _TipHub_SubscribeThread_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeNotifications",
			Handler:       _TipHub_SubscribeNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tip.proto",
}
