// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package lifecycle

import (
	"context"
	"os"
	"path/filepath"
	"strings"

	internalbackendbuilder "github.com/choysum-dev/choysum/internal/module/artifact/build/backend"
	module "github.com/choysum-dev/choysum/internal/module/artifact/result"
	"github.com/choysum-dev/choysum/internal/module/plan"
	"github.com/choysum-dev/choysum/pkg/meta"
	xfmt "golang.org/x/exp/errors/fmt"
)

func (m *ModuleManager) buildBackendBundlesToDir(ctx context.Context, distBundlesDir string, _ map[string]string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	runtimeOpts := m.resolvedRuntimeOptions()

	// Load all installed modules (needed for dependency graph + proto source selection).
	var installedMods []meta.Module
	if err := m.runtimeScope.Session().
		Where("status = ?", meta.Installed).
		Order("id ASC").
		Find(&installedMods).Error; err != nil {
		return xfmt.Errorf("error loading installed modules: %w", err)
	}

	// Load backend entry modules for each app in install order.
	// Include modules without ServiceEntryPoint so TranslationTerm Ensure can
	// still claim a host (e.g. application=web).
	var backendMods []meta.Module
	if err := m.runtimeScope.Session().
		Where("status = ? AND application_str <> '' AND path <> ''", meta.Installed).
		Order("id ASC").
		Find(&backendMods).Error; err != nil {
		return xfmt.Errorf("error loading backend modules: %w", err)
	}

	modsByApp := map[string][]*meta.Module{}
	for i := range backendMods {
		app := strings.TrimSpace(backendMods[i].ApplicationStr)
		if app == "" {
			continue
		}
		modsByApp[app] = append(modsByApp[app], &backendMods[i])
	}

	appsWithBackend := make([]string, 0, len(modsByApp))
	for app := range modsByApp {
		appsWithBackend = append(appsWithBackend, app)
	}

	orderedApps, cyclic := plan.StableTopoSortApplicationsForTargets(installedMods, appsWithBackend)
	if cyclic {
		m.runtimeScope.Logger().Warn("backend bundles topo order fallback", "reason", "application_dependency_cycle", "apps", orderedApps)
	}

	// Write a synthetic entry that imports all backend entries in install order.
	entryFilePath := filepath.Join(distBundlesDir, "__choysum_bundles_entry.ts")
	var b strings.Builder
	b.WriteString("// Generated by Choysum. DO NOT EDIT.\n")
	fieldDefaultOwners := make([]*meta.Module, 0, len(orderedApps))
	appSettingOwners := make([]*meta.Module, 0, len(orderedApps))
	translationTermOwners := make([]*meta.Module, 0, len(orderedApps))
	for _, app := range orderedApps {
		mods := modsByApp[app]
		if len(mods) == 0 {
			continue
		}
		for _, mod := range mods {
			if mod == nil {
				continue
			}
			entry := strings.TrimSpace(mod.ServiceEntryPoint)
			if entry == "" {
				continue
			}
			if !filepath.IsAbs(entry) {
				entry = filepath.Join(runtimeOpts.modulesPath, mod.Name, entry)
			}
			entry = filepath.Clean(entry)
			b.WriteString("import \"")
			b.WriteString(entry)
			b.WriteString("\";\n")
		}
		if owner := pickFieldDefaultOwnerModule(app, mods); owner != nil {
			fieldDefaultOwners = append(fieldDefaultOwners, owner)
		}
		if owner := pickAppSettingOwnerModule(app, mods); owner != nil {
			appSettingOwners = append(appSettingOwners, owner)
		}
		if owner := pickTranslationTermOwnerModule(app, mods); owner != nil {
			translationTermOwners = append(translationTermOwners, owner)
		}
	}
	if err := os.WriteFile(entryFilePath, []byte(b.String()), 0o644); err != nil {
		return xfmt.Errorf("write bundles entry: %w", err)
	}

	// Build bundles/index.js into distBundlesDir.
	if len(orderedApps) > 0 {
		mods := modsByApp[orderedApps[0]]
		if len(mods) == 0 {
			return nil
		}
		rep := mods[len(mods)-1]
		builder := internalbackendbuilder.NewModuleBuilder(
			m.runtimeScope,
			m.jsExecutor,
			rep,
			entryFilePath,
			internalbackendbuilder.WithGlobalName("bundles"),
			internalbackendbuilder.WithOutFileName("index.js"),
			internalbackendbuilder.WithPublishDist(true),
		)
		// Multi-app entry only Decide/Injects against `rep` (often core). Explicitly
		// re-register C2 FieldDefault / AppSetting virtual sources for every non-core
		// app so the final bundles/index.js actually contains the store classes.
		if err := ensureBundleC2VirtualImports(builder, fieldDefaultOwners, appSettingOwners, translationTermOwners); err != nil {
			return err
		}
		bundlerToDir, ok := builder.(module.BundlerToDir)
		if !ok {
			return xfmt.Errorf("backend builder does not support BundleToDirCtx")
		}
		if _, err := bundlerToDir.BundleToDirCtx(ctx, distBundlesDir); err != nil {
			return xfmt.Errorf("backend bundle failed for bundles: %w", err)
		}
	}

	return nil
}

// ensureBundleC2VirtualImports registers C2 inject sources on a multi-app bundle
// builder. Extracted for unit tests of error wrapping.
func ensureBundleC2VirtualImports(builder any, fieldDefaultOwners, appSettingOwners, translationTermOwners []*meta.Module) error {
	injector, ok := builder.(interface {
		BundleInjectAppModels([]*meta.Module) error
	})
	if !ok {
		return nil
	}
	// Owners are usually the same eligible backend modules; merge preserving order
	// and uniqueness so one BundleInjectAppModels covers every Spec.
	seen := make(map[string]struct{})
	owners := make([]*meta.Module, 0, len(fieldDefaultOwners)+len(appSettingOwners)+len(translationTermOwners))
	appendUnique := func(mods []*meta.Module) {
		for _, mod := range mods {
			if mod == nil {
				continue
			}
			key := strings.TrimSpace(mod.Name) + "\x00" + strings.TrimSpace(mod.Path)
			if key == "\x00" {
				continue
			}
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			owners = append(owners, mod)
		}
	}
	appendUnique(fieldDefaultOwners)
	appendUnique(appSettingOwners)
	appendUnique(translationTermOwners)
	if err := injector.BundleInjectAppModels(owners); err != nil {
		return xfmt.Errorf("inject app models for bundles: %w", err)
	}
	return nil
}

// pickFieldDefaultOwnerModule chooses which module path hosts the C2 FieldDefault
// virtual file for an application (one store per app).
//
// Prefer the last eligible backend module so the owner matches how the multi-app
// Bundle picks its representative (`mods[len-1]`). BundleInjectAppModels still
// rewrites the path to any existing generated meta row when present.
func pickFieldDefaultOwnerModule(app string, mods []*meta.Module) *meta.Module {
	app = strings.TrimSpace(app)
	if app == "" || app == "core" || len(mods) == 0 {
		return nil
	}
	var owner *meta.Module
	for _, mod := range mods {
		if mod == nil || strings.TrimSpace(mod.ServiceEntryPoint) == "" || strings.TrimSpace(mod.Path) == "" {
			continue
		}
		owner = mod
	}
	return owner
}

// pickAppSettingOwnerModule chooses which module path hosts the C2 AppSetting
// virtual file for an application (one store per app). Same selection rules as
// pickFieldDefaultOwnerModule.
func pickAppSettingOwnerModule(app string, mods []*meta.Module) *meta.Module {
	return pickFieldDefaultOwnerModule(app, mods)
}

// pickTranslationTermOwnerModule chooses the TranslationTerm host module.
// Unlike FieldDefault/AppSetting, empty ServiceEntryPoint is allowed (Ensure).
func pickTranslationTermOwnerModule(app string, mods []*meta.Module) *meta.Module {
	app = strings.TrimSpace(app)
	if app == "" || app == "core" || len(mods) == 0 {
		return nil
	}
	var withEntry, withoutEntry *meta.Module
	for _, mod := range mods {
		if mod == nil || strings.TrimSpace(mod.Path) == "" {
			continue
		}
		if strings.TrimSpace(mod.ServiceEntryPoint) != "" {
			withEntry = mod
		} else {
			withoutEntry = mod
		}
	}
	if withEntry != nil {
		return withEntry
	}
	return withoutEntry
}
