// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package lifecycle

import (
	"context"
	"os"
	"path/filepath"
	"strings"

	internalbackendbuilder "github.com/choysum-dev/choysum/internal/module/artifact/build/backend"
	module "github.com/choysum-dev/choysum/internal/module/artifact/result"
	"github.com/choysum-dev/choysum/internal/module/plan"
	"github.com/choysum-dev/choysum/pkg/meta"
	xfmt "golang.org/x/exp/errors/fmt"
)

func (m *ModuleManager) buildBackendBundlesToDir(ctx context.Context, distBundlesDir string, _ map[string]string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	runtimeOpts := m.resolvedRuntimeOptions()

	// Load all installed modules (needed for dependency graph + proto source selection).
	var installedMods []meta.IrModule
	if err := m.runtimeScope.Session().
		Where("status = ?", meta.Installed).
		Order("id ASC").
		Find(&installedMods).Error; err != nil {
		return xfmt.Errorf("error loading installed modules: %w", err)
	}

	// Load backend entry modules for each app in install order.
	var backendMods []meta.IrModule
	if err := m.runtimeScope.Session().
		Where("status = ? AND application_str <> '' AND service_entry_point <> ''", meta.Installed).
		Order("id ASC").
		Find(&backendMods).Error; err != nil {
		return xfmt.Errorf("error loading backend modules: %w", err)
	}

	modsByApp := map[string][]*meta.IrModule{}
	for i := range backendMods {
		app := strings.TrimSpace(backendMods[i].ApplicationStr)
		if app == "" {
			continue
		}
		modsByApp[app] = append(modsByApp[app], &backendMods[i])
	}

	appsWithBackend := make([]string, 0, len(modsByApp))
	for app := range modsByApp {
		appsWithBackend = append(appsWithBackend, app)
	}

	orderedApps, cyclic := plan.StableTopoSortApplicationsForTargets(installedMods, appsWithBackend)
	if cyclic {
		m.runtimeScope.Logger().Warn("backend bundles topo order fallback", "reason", "application_dependency_cycle", "apps", orderedApps)
	}

	// Write a synthetic entry that imports all backend entries in install order.
	entryFilePath := filepath.Join(distBundlesDir, "__choysum_bundles_entry.ts")
	var b strings.Builder
	b.WriteString("// Generated by Choysum. DO NOT EDIT.\n")
	for _, app := range orderedApps {
		mods := modsByApp[app]
		if len(mods) == 0 {
			continue
		}
		for _, mod := range mods {
			if mod == nil {
				continue
			}
			entry := strings.TrimSpace(mod.ServiceEntryPoint)
			if entry == "" {
				continue
			}
			if !filepath.IsAbs(entry) {
				entry = filepath.Join(runtimeOpts.modulesPath, mod.Name, entry)
			}
			entry = filepath.Clean(entry)
			b.WriteString("import \"")
			b.WriteString(entry)
			b.WriteString("\";\n")
		}
	}
	if err := os.WriteFile(entryFilePath, []byte(b.String()), 0o644); err != nil {
		return xfmt.Errorf("write bundles entry: %w", err)
	}

	// Build bundles/index.js into distBundlesDir.
	if len(orderedApps) > 0 {
		mods := modsByApp[orderedApps[0]]
		if len(mods) == 0 {
			return nil
		}
		rep := mods[len(mods)-1]
		builder := internalbackendbuilder.NewModuleBuilder(
			m.runtimeScope,
			m.jsExecutor,
			rep,
			entryFilePath,
			internalbackendbuilder.WithGlobalName("bundles"),
			internalbackendbuilder.WithOutFileName("index.js"),
			internalbackendbuilder.WithPublishDist(true),
		)
		bundlerToDir, ok := builder.(module.BundlerToDir)
		if !ok {
			return xfmt.Errorf("backend builder does not support BundleToDirCtx")
		}
		if _, err := bundlerToDir.BundleToDirCtx(ctx, distBundlesDir); err != nil {
			return xfmt.Errorf("backend bundle failed for bundles: %w", err)
		}
	}

	return nil
}
