// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package lifecycle

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	metadata "github.com/choysum-dev/choysum/internal/module/metadata"
	leasemodel "github.com/choysum-dev/choysum/internal/state/lease/model"

	"github.com/choysum-dev/choysum/internal/distmanifest"
	internalbackendbuilder "github.com/choysum-dev/choysum/internal/module/artifact/build/backend"
	internalwebmodulebuilder "github.com/choysum-dev/choysum/internal/module/artifact/build/web"
	modulegenerator "github.com/choysum-dev/choysum/internal/module/artifact/generate"
	modulemanifest "github.com/choysum-dev/choysum/internal/module/artifact/manifest"
	"github.com/choysum-dev/choysum/internal/module/artifact/pipeline"
	module "github.com/choysum-dev/choysum/internal/module/artifact/result"
	"github.com/choysum-dev/choysum/internal/module/artifact/staging"
	"github.com/choysum-dev/choysum/internal/module/evolution/scripts"
	moduleorigin "github.com/choysum-dev/choysum/internal/module/origin"
	"github.com/choysum-dev/choysum/internal/module/plan"
	"github.com/choysum-dev/choysum/internal/state/lease"
	"github.com/choysum-dev/choysum/pkg/config"
	"github.com/choysum-dev/choysum/pkg/jsexecutor"
	"github.com/choysum-dev/choysum/pkg/meta"
	"github.com/choysum-dev/choysum/pkg/oerrors"
	"github.com/choysum-dev/choysum/pkg/scope"
	statepkg "github.com/choysum-dev/choysum/pkg/state"
	"github.com/rs/xid"
	xfmt "golang.org/x/exp/errors/fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func (m *ModuleManager) generateAppToDirs(ctx context.Context, appName string, modulesTargets pipeline.ModulesAppTargets, distAppDir string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	if err := m.ensureMetaTables(); err != nil {
		return err
	}

	var mod meta.IrModule
	result := m.runtimeScope.Session().
		Where("application_str = ? AND status = ?", appName, meta.Installed).
		Order("name ASC").
		Take(&mod)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil
		}
		return xfmt.Errorf("error loading module for app %s: %w", appName, result.Error)
	}

	gen := modulegenerator.NewGrpcGenerator(m.runtimeScope, &mod)
	genToTargets, ok := gen.(module.GeneratorToTargets)
	if !ok {
		return xfmt.Errorf("generator does not support GenerateToTargetsCtx")
	}
	if _, err := genToTargets.GenerateToTargetsCtx(ctx, modulesTargets.ProtoDir, modulesTargets.WebDir, modulesTargets.ServiceDir, distAppDir); err != nil {
		return xfmt.Errorf("error generating app %s: %w", appName, err)
	}
	return nil
}

func (m *ModuleManager) buildBackendAppToDir(ctx context.Context, appName string, distAppDir string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	if err := m.ensureMetaTables(); err != nil {
		return err
	}

	var mods []meta.IrModule
	if err := m.runtimeScope.Session().
		Where("application_str = ? AND status = ? AND service_entry_point <> ''", appName, meta.Installed).
		Order("id ASC").
		Find(&mods).Error; err != nil {
		return xfmt.Errorf("error loading backend modules for app %s: %w", appName, err)
	}
	if len(mods) == 0 {
		return nil
	}
	runtimeOpts := m.resolvedRuntimeOptions()

	if err := os.MkdirAll(distAppDir, 0o755); err != nil {
		return xfmt.Errorf("create staging app dir %s: %w", distAppDir, err)
	}
	entryFilePath := filepath.Join(distAppDir, "__choysum_app_entry.ts")
	var b strings.Builder
	b.WriteString("// Generated by Choysum. DO NOT EDIT.\n")
	for i := range mods {
		entry := strings.TrimSpace(mods[i].ServiceEntryPoint)
		if entry == "" {
			continue
		}
		if !filepath.IsAbs(entry) {
			entry = filepath.Join(runtimeOpts.modulesPath, mods[i].Name, entry)
		}
		entry = filepath.Clean(entry)
		b.WriteString("import \"")
		b.WriteString(entry)
		b.WriteString("\";\n")
	}
	if err := os.WriteFile(entryFilePath, []byte(b.String()), 0o644); err != nil {
		return xfmt.Errorf("write app entry: %w", err)
	}

	// Use the last installed module as representative for build metadata.
	rep := &mods[len(mods)-1]
	builder := internalbackendbuilder.NewModuleBuilder(m.runtimeScope, m.jsExecutor, rep, entryFilePath, internalbackendbuilder.WithPublishDist(true))
	bundlerToDir, ok := builder.(module.BundlerToDir)
	if !ok {
		return xfmt.Errorf("backend builder does not support BundleToDirCtx")
	}
	if _, err := bundlerToDir.BundleToDirCtx(ctx, distAppDir); err != nil {
		return xfmt.Errorf("backend bundle failed for app %s: %w", appName, err)
	}
	return nil
}

func (m *ModuleManager) buildGlobalWebToDir(ctx context.Context, distWebDir string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	webMod, err := m.Load("web")
	if err != nil {
		return err
	}

	if webMod == nil || webMod.Status != meta.Installed || webMod.WebEntryPoint == "" {
		// No web module: leave staging empty; pipeline commit will replace dist/web.
		return nil
	}

	entry := webMod.WebEntryPoint
	runtimeOpts := m.resolvedRuntimeOptions()
	if !filepath.IsAbs(entry) {
		entry = filepath.Join(runtimeOpts.modulesPath, webMod.Name, entry)
	}
	webMod.WebEntryPoint = entry

	b := internalwebmodulebuilder.NewWebBuilder(m.runtimeScope, m.jsExecutor, webMod, entry)
	bToDir, ok := b.(module.BuilderToDir)
	if !ok {
		return xfmt.Errorf("web builder does not support BuildToDirCtx")
	}
	if _, err := bToDir.BuildToDirCtx(ctx, distWebDir); err != nil {
		return xfmt.Errorf("global web build failed: %w", err)
	}
	return nil
}

type ModuleManager struct {
	runtimeScope             scope.Scope
	runtimeOptions           runtimeOptions
	jsExecutor               jsexecutor.ScriptExecutor
	entities                 []any
	bootstrapOnce            sync.Once
	lockerFactory            statepkg.LockerFactory
	moduleIndexSyncLocal     func(ctx context.Context, runtimeScope scope.Scope, lockerFactory statepkg.LockerFactory) (ModuleIndexSyncStats, error)
	originCoordinatorFactory func(runtimeScope scope.Scope) OriginCoordinator
}

func (m *ModuleManager) ensureMetaTables() error {
	var migrateErr error
	m.bootstrapOnce.Do(func() {
		// Bootstrap meta tables in an isolated transaction that is committed
		// independently from any caller transaction.
		// This avoids visibility issues when the caller is already inside an open
		// transaction and another operation uses its own lease/meta transaction.
		txRoot := m.runtimeScope.WithContext(m.runtimeScope.Context())
		migrateErr = txRoot.Transactor().RequiresNew(txRoot.Context(), func(txScope scope.Scope, _ scope.Transaction) error {
			migrator := txScope.Session().Migrator()

			if migrator.HasTable(&meta.IrModule{}) && migrator.HasTable(&leasemodel.IrLockLease{}) {
				return nil
			}

			txScope.Logger().Info("meta base table bootstrap started")
			if err := txScope.Session().AutoMigrate(m.entities...); err != nil {
				return xfmt.Errorf("auto migrate meta entities: %w", err)
			}
			return nil
		})
	})
	return migrateErr
}

func (m *ModuleManager) withModuleManagerLease(ctx context.Context, fn func() error) error {
	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	if ctx == nil {
		ctx = context.Background()
	}

	locker := m.lockerFactory(m.runtimeScope)
	resource := "module_management"
	ownerId := xid.New().String()
	ttl := 60 * time.Second

	if err := locker.Acquire(ctx, resource, ownerId, ttl); err != nil {
		if errors.Is(err, lease.ErrLeaseBusy) {
			retryAfterMs := int64(ttl / time.Millisecond)
			return oerrors.New("meta.lock", "LEASE_CONFLICT", "lease is busy").WithMetadata("retry_after_ms", fmt.Sprintf("%d", retryAfterMs))
		}
		return err
	}

	heartbeatCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	done := make(chan struct{})
	go func() {
		defer close(done)
		ticker := time.NewTicker(ttl / 2)
		defer ticker.Stop()
		for {
			select {
			case <-heartbeatCtx.Done():
				return
			case <-ticker.C:
				if err := locker.Renew(heartbeatCtx, resource, ownerId, ttl); err != nil {
					m.runtimeScope.Logger().Warn("module manager lease renew failed", "resource", resource, "error", err)
				}
			}
		}
	}()

	defer func() {
		cancel()
		<-done
		releaseCtx, releaseCancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer releaseCancel()
		if err := locker.Release(releaseCtx, resource, ownerId); err != nil {
			m.runtimeScope.Logger().Warn("module manager lease release failed", "resource", resource, "error", err)
		}
	}()

	return fn()
}

func (m *ModuleManager) migrateBaseModule() error {
	m.runtimeScope.Logger().Debug("base module entity migration started")
	if err := m.runtimeScope.Session().AutoMigrate(
		m.entities...,
	); err != nil {
		return xfmt.Errorf("error migrating base module: %w", err)
	}
	return nil
}

func (m *ModuleManager) resolveInstallModuleFromOrigin(ctx context.Context, name string) (*meta.IrModule, error) {
	if err := m.ensureMetaTables(); err != nil {
		return nil, err
	}
	if ctx == nil {
		ctx = context.Background()
	}
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, xfmt.Errorf("module name is empty")
	}

	coordinator := m.newOriginCoordinator()
	module, err := coordinator.ResolveInstallModule(ctx, name)
	if err != nil {
		return nil, xfmt.Errorf("error resolving module %s from origin: %w", name, err)
	}

	if meta.IsCoreModule(module.Name) {
		if err := m.migrateBaseModule(); err != nil {
			return nil, err
		}
	}

	return module, nil
}

func (m *ModuleManager) Peek(ctx context.Context, name string) (*meta.IrModule, error) {
	if err := m.ensureMetaTables(); err != nil {
		return nil, err
	}
	if ctx == nil {
		ctx = context.Background()
	}
	coordinator := m.newOriginCoordinator()
	module, err := coordinator.Peek(ctx, name)
	if err != nil {
		return nil, xfmt.Errorf("error peeking module %s: %w", name, err)
	}
	return module, nil
}

func (m *ModuleManager) Load(name string) (*meta.IrModule, error) {
	if err := m.ensureMetaTables(); err != nil {
		return nil, err
	}

	if meta.IsCoreModule(name) {
		if err := m.migrateBaseModule(); err != nil {
			return nil, err
		}
	}

	var module meta.IrModule
	if result := m.runtimeScope.Session().
		Preload("Dependencies", func(db *gorm.DB) *gorm.DB { return db.Where("status = ?", meta.Installed).Order("id ASC") }).
		Preload("Dependents", func(db *gorm.DB) *gorm.DB { return db.Where("status = ?", meta.Installed).Order("id ASC") }).
		Where("name = ?", name).Take(&module); result.Error != nil {
		if !errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, xfmt.Errorf("error loading module %s: %w", name, result.Error)
		} else {
			return nil, nil
		}
	}
	return &module, nil
}

func ensureOpIDInContext(ctx context.Context) (context.Context, string) {
	if ctx == nil {
		ctx = context.Background()
	}
	if opid, ok := staging.OpIDFromContext(ctx); ok {
		return ctx, opid
	}
	opid := staging.NewOpID()
	return staging.WithOpID(ctx, opid), opid
}

func moduleOpLogger(logger *slog.Logger, opid string, op plan.OpType, moduleName string) *slog.Logger {
	if logger == nil {
		logger = slog.Default()
	}
	attrs := []any{"opid", opid, "op", string(op), "module", moduleName}
	return logger.With(attrs...)
}

const moduleOpInfoNameListLimit = 8

func summarizeModuleOpInfoNames(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(values))
	compact := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			return nil
		}
		if _, ok := seen[value]; ok {
			return nil
		}
		seen[value] = struct{}{}
		compact = append(compact, value)
	}
	if len(compact) == 0 || len(compact) > moduleOpInfoNameListLimit {
		return nil
	}
	return compact
}

func moduleOperationPlanInfoAttrs(opPlan plan.Plan) []any {
	attrs := []any{
		"modules_count", len(opPlan.ModuleOrder),
		"apps_count", len(opPlan.AffectedApps),
		"needs_global_web_build", opPlan.NeedsGlobalWebBuild,
	}
	if modules := summarizeModuleOpInfoNames(opPlan.ModuleOrder); len(modules) > 0 {
		attrs = append(attrs, "modules", modules)
	}
	if apps := summarizeModuleOpInfoNames(opPlan.AffectedApps); len(apps) > 0 {
		attrs = append(attrs, "apps", apps)
	}
	return attrs
}

func moduleOperationCompletedInfoAttrs(opPlan plan.Plan, duration time.Duration) []any {
	attrs := []any{
		"duration_ms", duration.Milliseconds(),
		"modules_count", len(opPlan.ModuleOrder),
		"apps_count", len(opPlan.AffectedApps),
	}
	if modules := summarizeModuleOpInfoNames(opPlan.ModuleOrder); len(modules) > 0 {
		attrs = append(attrs, "modules", modules)
	}
	if apps := summarizeModuleOpInfoNames(opPlan.AffectedApps); len(apps) > 0 {
		attrs = append(attrs, "apps", apps)
	}
	return attrs
}

func nullString(value string) sql.NullString {
	value = strings.TrimSpace(value)
	if value == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: value, Valid: true}
}

func (m *ModuleManager) resolveGeneratedAPIRoot() (string, error) {
	runtimeOpts := m.resolvedRuntimeOptions()
	generatedAPIRoot, err := modulegenerator.WorkspaceGeneratedAPIRoot(runtimeOpts.modulesPath, runtimeOpts.defaultChoysumPath)
	if err != nil {
		return "", xfmt.Errorf("resolve workspace generated api root: %w", err)
	}
	return generatedAPIRoot, nil
}

func (m *ModuleManager) refreshModuleIndexForLocalModules(ctx context.Context, moduleNames []string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if len(moduleNames) == 0 {
		return nil
	}

	runtimeOpts := m.resolvedRuntimeOptions()
	modulesPath := strings.TrimSpace(runtimeOpts.modulesPath)
	now := time.Now()
	seen := make(map[string]struct{}, len(moduleNames))

	for _, raw := range moduleNames {
		name := strings.TrimSpace(raw)
		if name == "" {
			continue
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}

		packageJSONPath := filepath.Join(modulesPath, name, "package.json")
		packageJSONData, readErr := os.ReadFile(packageJSONPath)

		entry := metadata.IrModuleIndex{
			ModuleName:       name,
			OriginType:       "local",
			OriginRef:        "local",
			Available:        readErr == nil,
			ManifestJson:     packageJSONData,
			LocalPath:        nullString(filepath.Join(modulesPath, name)),
			LastSyncAt:       &now,
			LastErrorMessage: nullString(""),
		}
		if readErr != nil {
			entry.ManifestJson = nil
			entry.LastErrorMessage = nullString("package.json not found")
		}

		mod, loadErr := m.Load(name)
		if loadErr != nil {
			m.runtimeScope.Logger().Warn("module load during index refresh failed", "module", name, "error", loadErr)
		} else if mod != nil {
			entry.Version = nullString(mod.Version)
		}

		if err := m.runtimeScope.Session().WithContext(ctx).
			Clauses(clause.OnConflict{
				Columns:   []clause.Column{{Name: "module_name"}, {Name: "origin_type"}, {Name: "origin_ref"}},
				DoUpdates: clause.AssignmentColumns([]string{"available", "version", "manifest_json", "local_path", "last_sync_at", "last_error_message"}),
			}).
			Create(&entry).Error; err != nil {
			return xfmt.Errorf("refresh module index for %s: %w", name, err)
		}
	}

	return nil
}

func containsModuleName(moduleNames []string, target string) bool {
	target = strings.TrimSpace(target)
	if target == "" {
		return false
	}
	for _, moduleName := range moduleNames {
		if strings.EqualFold(strings.TrimSpace(moduleName), target) {
			return true
		}
	}
	return false
}

func (m *ModuleManager) syncModuleIndexAfterInstall(ctx context.Context, logger *slog.Logger, moduleNames []string) error {
	if !containsModuleName(moduleNames, "meta") {
		return nil
	}
	syncFn := m.moduleIndexSyncLocal
	if syncFn == nil {
		syncFn = SyncLocalModuleIndex
	}
	if _, err := syncFn(ctx, m.runtimeScope, m.lockerFactory); err != nil {
		if logger != nil {
			logger.Warn("module index sync after meta install failed", "error", err)
		}
	}
	return nil
}

func (m *ModuleManager) Install(ctx context.Context, name string) error {
	return m.withModuleManagerLease(ctx, func() error {
		ctx, opid := ensureOpIDInContext(ctx)
		name = strings.TrimSpace(name)
		if name == "" {
			return xfmt.Errorf("module name is empty")
		}

		rootModule, err := m.resolveInstallModuleFromOrigin(ctx, name)
		if err != nil {
			return err
		}
		if rootModule == nil {
			return xfmt.Errorf("module %s not found in origin", name)
		}

		moduleName := strings.TrimSpace(rootModule.Name)
		if moduleName == "" {
			return xfmt.Errorf("resolved module name is empty")
		}

		// Idempotent fast-path: if the module is already installed AND all declared
		// dependencies are installed, treat `install` as a no-op (no rebuild).
		existing, err := m.Load(moduleName)
		if err != nil {
			return err
		}
		if existing != nil && existing.Status == meta.Installed {
			depsOK := true
			if len(existing.DependsStr) > 0 {
				var deps []string
				if err := json.Unmarshal(existing.DependsStr, &deps); err != nil {
					return xfmt.Errorf("unmarshal depends for %s: %w", moduleName, err)
				}
				seen := map[string]bool{}
				for _, dep := range deps {
					dep = strings.TrimSpace(dep)
					if dep == "" || seen[dep] {
						continue
					}
					seen[dep] = true
					depMod, err := m.Load(dep)
					if err != nil {
						return err
					}
					if depMod == nil || depMod.Status != meta.Installed {
						depsOK = false
						break
					}
				}
			}
			if depsOK {
				logger := moduleOpLogger(m.runtimeScope.Logger(), opid, plan.OpInstall, moduleName)
				logger.Info("module operation skipped", "reason", "already_installed")
				return nil
			}
		}

		runtimeOpts := m.resolvedRuntimeOptions()
		opCtx := newOpContext()
		opCtx.withDemo = OperationOptionsFromContext(ctx).WithDemo
		opCtx.opid = opid
		stageCtx := staging.WithTmpRoot(ctx, runtimeOpts.tmpPath)
		generatedAPIRoot, err := m.resolveGeneratedAPIRoot()
		if err != nil {
			return err
		}
		if err := staging.CleanupCrashArtifacts(stageCtx, []string{
			runtimeOpts.distPath,
			generatedAPIRoot,
		}, opid); err != nil {
			return err
		}
		plan, err := plan.BuildPlan(ctx, plan.OpInstall, rootModule, m)
		if err != nil {
			return err
		}
		logger := moduleOpLogger(m.runtimeScope.Logger(), opid, plan.Op, rootModule.Name)
		logger.Info("module operation plan", moduleOperationPlanInfoAttrs(plan)...)
		logger.Debug("module operation plan details", "modules", plan.ModuleOrder, "apps", plan.AffectedApps)
		isBundleMode := strings.EqualFold(strings.TrimSpace(runtimeOpts.compileBundleMode), "bundle")
		var bundlesTargetFn func() (string, error)
		var buildBundlesFn func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error
		if isBundleMode {
			bundlesTargetFn = func() (string, error) { return config.BundlesDir(runtimeOpts.distPath), nil }
			buildBundlesFn = func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error {
				return m.buildBackendBundlesToDir(stageCtx, distBundlesStagingDir, affectedProtoStaging)
			}
		}
		started := time.Now()
		err = pipeline.Execute(stageCtx, plan, rootModule, pipeline.Callbacks{
			Logger:                         logger,
			ResolveInstallModuleFromOrigin: m.resolveInstallModuleFromOrigin,
			ResolveInstalledModule:         m.Load,
			Install: func(mod *meta.IrModule) error {
				return m.installWithCtx(mod, opCtx)
			},
			Uninstall: func(mod *meta.IrModule) error {
				return m.uninstallWithCtx(mod, opCtx)
			},
			Upgrade: func(mod *meta.IrModule) error {
				return m.upgradeWithCtx(mod, opCtx)
			},
			AppTargets: func(appName string) (string, pipeline.ModulesAppTargets, error) {
				distAppDir := ""
				if !isBundleMode {
					distAppDir = config.AppDir(runtimeOpts.distPath, appName)
				}
				protoDir := filepath.Join(generatedAPIRoot, "proto", appName)
				webDir := filepath.Join(generatedAPIRoot, "web", appName)
				serviceDir := filepath.Join(generatedAPIRoot, "service", appName)
				modulesTargets := pipeline.ModulesAppTargets{
					ProtoDir:        protoDir,
					WebDir:          webDir,
					ServiceDir:      serviceDir,
					RuntimeProtoDir: config.APIAppProtoDir(runtimeOpts.distPath, appName),
				}
				return distAppDir, modulesTargets, nil
			},
			BundlesTarget: bundlesTargetFn,
			WebTarget: func() (string, error) {
				return config.WebDir(runtimeOpts.distPath), nil
			},
			DistManifestTarget: func() (string, error) {
				return filepath.Join(runtimeOpts.distPath, distmanifest.DistManifestFileName), nil
			},
			WriteDistManifest: func(stageCtx context.Context, distManifestStagingPath string) error {
				return modulemanifest.WriteDistManifest(stageCtx, m.runtimeScope, runtimeOpts.compileBundleMode, distManifestStagingPath)
			},
			BuildBackendApp: func(stageCtx context.Context, appName string, distAppStagingDir string) error {
				return m.buildBackendAppToDir(stageCtx, appName, distAppStagingDir)
			},
			GenerateApp: func(stageCtx context.Context, appName string, modulesStaging pipeline.ModulesAppTargets, distAppStagingDir string) error {
				return m.generateAppToDirs(stageCtx, appName, modulesStaging, distAppStagingDir)
			},
			BuildBackendBundles: buildBundlesFn,
			GlobalWebBuild: func(stageCtx context.Context, distWebStagingDir string) error {
				return m.buildGlobalWebToDir(stageCtx, distWebStagingDir)
			},
		})
		if err != nil {
			return err
		}
		for _, name := range plan.ModuleOrder {
			mod, err := m.Load(name)
			if err != nil {
				return err
			}
			if mod == nil {
				continue
			}
			fromVersion := ""
			if opCtx != nil {
				fromVersion = opCtx.getFromVersion(name)
			}
			if runner := scripts.NewRunner(m.runtimeScope, m.jsExecutor, mod); runner != nil {
				if err := runner.RunPhase(m.runtimeScope.Context(), scripts.RunOptions{Phase: scripts.PhaseEnd, FromVersion: fromVersion, ToVersion: mod.Version}); err != nil {
					return err
				}
			}
		}
		if err := m.refreshModuleIndexForLocalModules(ctx, plan.ModuleOrder); err != nil {
			return err
		}
		if err := m.syncModuleIndexAfterInstall(ctx, logger, plan.ModuleOrder); err != nil {
			return err
		}
		logger.Info("module operation completed", moduleOperationCompletedInfoAttrs(plan, time.Since(started))...)
		return nil
	})
}

func (m *ModuleManager) Uninstall(ctx context.Context, name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return xfmt.Errorf("module name is empty")
	}
	mod, err := m.Load(name)
	if err != nil {
		return err
	}
	if mod == nil {
		return xfmt.Errorf("module %s not found", name)
	}

	return m.withModuleManagerLease(ctx, func() error {
		ctx, opid := ensureOpIDInContext(ctx)

		runtimeOpts := m.resolvedRuntimeOptions()
		opCtx := newOpContext()
		opCtx.withDemo = OperationOptionsFromContext(ctx).WithDemo
		opCtx.opid = opid
		stageCtx := staging.WithTmpRoot(ctx, runtimeOpts.tmpPath)
		generatedAPIRoot, err := m.resolveGeneratedAPIRoot()
		if err != nil {
			return err
		}
		if err := staging.CleanupCrashArtifacts(stageCtx, []string{
			runtimeOpts.distPath,
			generatedAPIRoot,
		}, opid); err != nil {
			return err
		}
		plan, err := plan.BuildPlan(ctx, plan.OpUninstall, mod, m)
		if err != nil {
			return err
		}
		logger := moduleOpLogger(m.runtimeScope.Logger(), opid, plan.Op, mod.Name)
		logger.Info("module operation plan", moduleOperationPlanInfoAttrs(plan)...)
		logger.Debug("module operation plan details", "modules", plan.ModuleOrder, "apps", plan.AffectedApps)
		isBundleMode := strings.EqualFold(strings.TrimSpace(runtimeOpts.compileBundleMode), "bundle")
		var bundlesTargetFn func() (string, error)
		var buildBundlesFn func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error
		if isBundleMode {
			bundlesTargetFn = func() (string, error) { return config.BundlesDir(runtimeOpts.distPath), nil }
			buildBundlesFn = func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error {
				return m.buildBackendBundlesToDir(stageCtx, distBundlesStagingDir, affectedProtoStaging)
			}
		}
		started := time.Now()
		err = pipeline.Execute(stageCtx, plan, mod, pipeline.Callbacks{
			Logger:                 logger,
			ResolveInstalledModule: m.Load,
			Install: func(mod *meta.IrModule) error {
				return m.installWithCtx(mod, opCtx)
			},
			Uninstall: func(mod *meta.IrModule) error {
				// Avoid cascading dependency upgrades during uninstall; it can cause cycles and storms.
				return m.uninstallWithCtx(mod, opCtx)
			},
			Upgrade: func(mod *meta.IrModule) error {
				return m.upgradeWithCtx(mod, opCtx)
			},
			AppTargets: func(appName string) (string, pipeline.ModulesAppTargets, error) {
				distAppDir := ""
				if !isBundleMode {
					distAppDir = config.AppDir(runtimeOpts.distPath, appName)
				}
				protoDir := filepath.Join(generatedAPIRoot, "proto", appName)
				webDir := filepath.Join(generatedAPIRoot, "web", appName)
				serviceDir := filepath.Join(generatedAPIRoot, "service", appName)
				modulesTargets := pipeline.ModulesAppTargets{
					ProtoDir:        protoDir,
					WebDir:          webDir,
					ServiceDir:      serviceDir,
					RuntimeProtoDir: config.APIAppProtoDir(runtimeOpts.distPath, appName),
				}
				return distAppDir, modulesTargets, nil
			},
			BundlesTarget: bundlesTargetFn,
			WebTarget: func() (string, error) {
				return config.WebDir(runtimeOpts.distPath), nil
			},
			DistManifestTarget: func() (string, error) {
				return filepath.Join(runtimeOpts.distPath, distmanifest.DistManifestFileName), nil
			},
			WriteDistManifest: func(stageCtx context.Context, distManifestStagingPath string) error {
				return modulemanifest.WriteDistManifest(stageCtx, m.runtimeScope, runtimeOpts.compileBundleMode, distManifestStagingPath)
			},
			BuildBackendApp: func(stageCtx context.Context, appName string, distAppStagingDir string) error {
				return m.buildBackendAppToDir(stageCtx, appName, distAppStagingDir)
			},
			GenerateApp: func(stageCtx context.Context, appName string, modulesStaging pipeline.ModulesAppTargets, distAppStagingDir string) error {
				return m.generateAppToDirs(stageCtx, appName, modulesStaging, distAppStagingDir)
			},
			BuildBackendBundles: buildBundlesFn,
			GlobalWebBuild: func(stageCtx context.Context, distWebStagingDir string) error {
				return m.buildGlobalWebToDir(stageCtx, distWebStagingDir)
			},
		})
		if err != nil {
			return err
		}
		logger.Info("module operation completed", moduleOperationCompletedInfoAttrs(plan, time.Since(started))...)
		return nil
	})
}

func (m *ModuleManager) Upgrade(ctx context.Context, name string) error {
	input := strings.TrimSpace(name)
	if input == "" {
		return xfmt.Errorf("module name is empty")
	}

	parsed, err := moduleorigin.ParseInput(input)
	if err != nil {
		return xfmt.Errorf("error parsing module input %s: %w", input, err)
	}
	moduleName := strings.TrimSpace(parsed.LocalName)
	if parsed.Kind == moduleorigin.InputKindRegistry {
		moduleName = strings.TrimSpace(parsed.ModuleName)
	}
	if moduleName == "" {
		return xfmt.Errorf("module name is empty")
	}
	if parsed.Kind == moduleorigin.InputKindLocal {
		mod, loadErr := m.Load(moduleName)
		if loadErr != nil {
			return loadErr
		}
		if mod == nil {
			return xfmt.Errorf("module %s not found (maybe uninstalled); use `install %s`", moduleName, moduleName)
		}
	}
	if parsed.Kind == moduleorigin.InputKindRegistry {
		coordinator := m.newOriginCoordinator()
		if _, peekErr := coordinator.Peek(ctx, input); peekErr != nil {
			return peekErr
		}
	}

	return m.withModuleManagerLease(ctx, func() error {
		ctx, opid := ensureOpIDInContext(ctx)

		originSwitch, err := m.prepareUpgradeOriginSwitch(ctx, parsed, moduleName, opid)
		if err != nil {
			return err
		}
		rollbackUpgradeOrigin := func(mainErr error) error {
			if mainErr == nil || originSwitch == nil {
				return mainErr
			}
			if rollbackErr := originSwitch.Rollback(); rollbackErr != nil {
				return xfmt.Errorf("upgrade failed: %w; origin rollback failed: %v", mainErr, rollbackErr)
			}
			return mainErr
		}

		mod, err := m.Load(moduleName)
		if err != nil {
			return rollbackUpgradeOrigin(err)
		}
		if mod == nil {
			return rollbackUpgradeOrigin(xfmt.Errorf("module %s not found (maybe uninstalled); use `install %s`", moduleName, moduleName))
		}

		runtimeOpts := m.resolvedRuntimeOptions()
		opCtx := newOpContext()
		opCtx.withDemo = OperationOptionsFromContext(ctx).WithDemo
		opCtx.opid = opid
		stageCtx := staging.WithTmpRoot(ctx, runtimeOpts.tmpPath)
		generatedAPIRoot, err := m.resolveGeneratedAPIRoot()
		if err != nil {
			return rollbackUpgradeOrigin(err)
		}
		if err := staging.CleanupCrashArtifacts(stageCtx, []string{
			runtimeOpts.distPath,
			generatedAPIRoot,
		}, opid); err != nil {
			return rollbackUpgradeOrigin(err)
		}
		plan, err := plan.BuildPlan(ctx, plan.OpUpgrade, mod, m)
		if err != nil {
			return rollbackUpgradeOrigin(err)
		}
		if meta.IsCoreModule(mod.Name) {
			apps, err := m.listInstalledNonWebApps(ctx)
			if err != nil {
				return rollbackUpgradeOrigin(err)
			}
			if len(apps) > 0 {
				plan.AffectedApps = apps
			}
		}
		logger := moduleOpLogger(m.runtimeScope.Logger(), opid, plan.Op, mod.Name)
		logger.Info("module operation plan", moduleOperationPlanInfoAttrs(plan)...)
		logger.Debug("module operation plan details", "modules", plan.ModuleOrder, "apps", plan.AffectedApps)
		isBundleMode := strings.EqualFold(strings.TrimSpace(runtimeOpts.compileBundleMode), "bundle")
		var bundlesTargetFn func() (string, error)
		var buildBundlesFn func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error
		if isBundleMode {
			bundlesTargetFn = func() (string, error) { return config.BundlesDir(runtimeOpts.distPath), nil }
			buildBundlesFn = func(stageCtx context.Context, distBundlesStagingDir string, affectedProtoStaging map[string]string) error {
				return m.buildBackendBundlesToDir(stageCtx, distBundlesStagingDir, affectedProtoStaging)
			}
		}
		started := time.Now()
		err = pipeline.Execute(stageCtx, plan, mod, pipeline.Callbacks{
			Logger:                 logger,
			ResolveInstalledModule: m.Load,
			Upgrade: func(mod *meta.IrModule) error {
				return m.upgradeWithCtx(mod, opCtx)
			},
			AppTargets: func(appName string) (string, pipeline.ModulesAppTargets, error) {
				distAppDir := ""
				if !isBundleMode {
					distAppDir = config.AppDir(runtimeOpts.distPath, appName)
				}
				protoDir := filepath.Join(generatedAPIRoot, "proto", appName)
				webDir := filepath.Join(generatedAPIRoot, "web", appName)
				serviceDir := filepath.Join(generatedAPIRoot, "service", appName)
				modulesTargets := pipeline.ModulesAppTargets{
					ProtoDir:        protoDir,
					WebDir:          webDir,
					ServiceDir:      serviceDir,
					RuntimeProtoDir: config.APIAppProtoDir(runtimeOpts.distPath, appName),
				}
				return distAppDir, modulesTargets, nil
			},
			BundlesTarget: bundlesTargetFn,
			WebTarget: func() (string, error) {
				return config.WebDir(runtimeOpts.distPath), nil
			},
			DistManifestTarget: func() (string, error) {
				return filepath.Join(runtimeOpts.distPath, distmanifest.DistManifestFileName), nil
			},
			WriteDistManifest: func(stageCtx context.Context, distManifestStagingPath string) error {
				return modulemanifest.WriteDistManifest(stageCtx, m.runtimeScope, runtimeOpts.compileBundleMode, distManifestStagingPath)
			},
			BuildBackendApp: func(stageCtx context.Context, appName string, distAppStagingDir string) error {
				return m.buildBackendAppToDir(stageCtx, appName, distAppStagingDir)
			},
			GenerateApp: func(stageCtx context.Context, appName string, modulesStaging pipeline.ModulesAppTargets, distAppStagingDir string) error {
				return m.generateAppToDirs(stageCtx, appName, modulesStaging, distAppStagingDir)
			},
			BuildBackendBundles: buildBundlesFn,
			GlobalWebBuild: func(stageCtx context.Context, distWebStagingDir string) error {
				return m.buildGlobalWebToDir(stageCtx, distWebStagingDir)
			},
		})
		if err != nil {
			return rollbackUpgradeOrigin(err)
		}
		for _, moduleName := range plan.ModuleOrder {
			mod, err := m.Load(moduleName)
			if err != nil {
				return rollbackUpgradeOrigin(err)
			}
			if mod == nil {
				continue
			}
			fromVersion := ""
			if opCtx != nil {
				fromVersion = opCtx.getFromVersion(moduleName)
			}
			if runner := scripts.NewRunner(m.runtimeScope, m.jsExecutor, mod); runner != nil {
				if err := runner.RunPhase(m.runtimeScope.Context(), scripts.RunOptions{Phase: scripts.PhaseEnd, FromVersion: fromVersion, ToVersion: mod.Version}); err != nil {
					return rollbackUpgradeOrigin(err)
				}
			}
		}
		if err := m.refreshModuleIndexForLocalModules(ctx, plan.ModuleOrder); err != nil {
			return rollbackUpgradeOrigin(err)
		}
		if originSwitch != nil {
			if err := originSwitch.Commit(); err != nil {
				return xfmt.Errorf("upgrade succeeded but origin cleanup failed: %w", err)
			}
		}
		logger.Info("module operation completed", moduleOperationCompletedInfoAttrs(plan, time.Since(started))...)
		return nil
	})
}

func (m *ModuleManager) listInstalledNonWebApps(ctx context.Context) ([]string, error) {
	if ctx == nil {
		ctx = context.Background()
	}

	var names []string
	if err := m.runtimeScope.Session().WithContext(ctx).
		Model(&meta.IrModule{}).
		Where("status = ?", meta.Installed).
		Where("application_str <> ''").
		Distinct("application_str").
		Pluck("application_str", &names).Error; err != nil {
		return nil, xfmt.Errorf("list installed apps: %w", err)
	}

	apps := make([]string, 0, len(names))
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" || strings.EqualFold(name, "web") {
			continue
		}
		apps = append(apps, name)
	}

	sort.Strings(apps)
	return apps, nil
}

func (m *ModuleManager) installWithCtx(module *meta.IrModule, ctx *opContext) error {
	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	if ctx.isInstallDone(module.Name) {
		return nil
	}
	if cycle := ctx.pushInstall(module.Name); cycle != nil {
		return xfmt.Errorf("dependency cycle detected: %s", strings.Join(cycle, " -> "))
	}
	defer ctx.popInstall(module.Name)

	installer := newModuleInstaller(m.runtimeScope, m.jsExecutor, module, m, ctx)
	if err := installer.install(); err != nil {
		return xfmt.Errorf("error installing module %s: %w", module.Name, err)
	}
	ctx.markInstallDone(module.Name)
	return nil
}

func (m *ModuleManager) uninstallWithCtx(module *meta.IrModule, ctx *opContext) error {
	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	if ctx.isUninstallDone(module.Name) {
		return nil
	}
	if cycle := ctx.pushUninstall(module.Name); cycle != nil {
		return xfmt.Errorf("dependency cycle detected while uninstalling: %s", strings.Join(cycle, " -> "))
	}
	defer ctx.popUninstall(module.Name)

	uninstaller := newModuleUninstaller(m.runtimeScope, module, m, ctx)
	if err := uninstaller.uninstall(); err != nil {
		return xfmt.Errorf("error uninstalling module %s: %w", module.Name, err)
	}
	ctx.markUninstallDone(module.Name)
	return nil
}

func (m *ModuleManager) upgradeWithCtx(module *meta.IrModule, ctx *opContext) error {
	if err := m.ensureMetaTables(); err != nil {
		return err
	}
	if ctx.isUpgradeDone(module.Name) {
		return nil
	}
	if cycle := ctx.pushUpgrade(module.Name); cycle != nil {
		return xfmt.Errorf("dependency cycle detected while upgrading: %s", strings.Join(cycle, " -> "))
	}
	defer ctx.popUpgrade(module.Name)

	upgrader := newModuleUpgrader(m.runtimeScope, module, m, ctx)
	if err := upgrader.upgrade(); err != nil {
		return xfmt.Errorf("error upgrading module %s: %w", module.Name, err)
	}
	ctx.markUpgradeDone(module.Name)
	return nil
}

func NewModuleManager(runtimeScope scope.Scope, jsExecutor jsexecutor.ScriptExecutor, opts ...Option) *ModuleManager {
	m := &ModuleManager{
		runtimeScope:   runtimeScope,
		runtimeOptions: runtimeOptionsFromScope(runtimeScope),
		jsExecutor:     jsExecutor,
		lockerFactory: func(runtimeScope scope.Scope) statepkg.Locker {
			return lease.New(runtimeScope)
		},
		moduleIndexSyncLocal: SyncLocalModuleIndex,
	}

	// Default entity set: shared IR, module admin/ops, and lease models.
	m.entities = append(meta.Entities(), metadata.Entities()...)
	m.entities = append(m.entities, leasemodel.Entities()...)

	// Apply external injections.
	for _, opt := range opts {
		opt(m)
	}
	return m
}
