// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: export.proto

package exportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportMode int32

const (
	ExportMode_EXPORT_MODE_UNSPECIFIED ExportMode = 0
	ExportMode_EXPORT_MODE_DATA        ExportMode = 1
	ExportMode_EXPORT_MODE_TEMPLATE    ExportMode = 2
)

// Enum value maps for ExportMode.
var (
	ExportMode_name = map[int32]string{
		0: "EXPORT_MODE_UNSPECIFIED",
		1: "EXPORT_MODE_DATA",
		2: "EXPORT_MODE_TEMPLATE",
	}
	ExportMode_value = map[string]int32{
		"EXPORT_MODE_UNSPECIFIED": 0,
		"EXPORT_MODE_DATA":        1,
		"EXPORT_MODE_TEMPLATE":    2,
	}
)

func (x ExportMode) Enum() *ExportMode {
	p := new(ExportMode)
	*p = x
	return p
}

func (x ExportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_export_proto_enumTypes[0].Descriptor()
}

func (ExportMode) Type() protoreflect.EnumType {
	return &file_export_proto_enumTypes[0]
}

func (x ExportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportMode.Descriptor instead.
func (ExportMode) EnumDescriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

type ExportMessageType int32

const (
	ExportMessageType_EXPORT_MESSAGE_TYPE_UNSPECIFIED ExportMessageType = 0
	ExportMessageType_EXPORT_MESSAGE_TYPE_ERROR       ExportMessageType = 1
	ExportMessageType_EXPORT_MESSAGE_TYPE_WARNING     ExportMessageType = 2
	ExportMessageType_EXPORT_MESSAGE_TYPE_SKIP        ExportMessageType = 3
)

// Enum value maps for ExportMessageType.
var (
	ExportMessageType_name = map[int32]string{
		0: "EXPORT_MESSAGE_TYPE_UNSPECIFIED",
		1: "EXPORT_MESSAGE_TYPE_ERROR",
		2: "EXPORT_MESSAGE_TYPE_WARNING",
		3: "EXPORT_MESSAGE_TYPE_SKIP",
	}
	ExportMessageType_value = map[string]int32{
		"EXPORT_MESSAGE_TYPE_UNSPECIFIED": 0,
		"EXPORT_MESSAGE_TYPE_ERROR":       1,
		"EXPORT_MESSAGE_TYPE_WARNING":     2,
		"EXPORT_MESSAGE_TYPE_SKIP":        3,
	}
)

func (x ExportMessageType) Enum() *ExportMessageType {
	p := new(ExportMessageType)
	*p = x
	return p
}

func (x ExportMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_export_proto_enumTypes[1].Descriptor()
}

func (ExportMessageType) Type() protoreflect.EnumType {
	return &file_export_proto_enumTypes[1]
}

func (x ExportMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportMessageType.Descriptor instead.
func (ExportMessageType) EnumDescriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

type ExportStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Ok            int32                  `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         int32                  `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Skip          int32                  `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	Warning       int32                  `protobuf:"varint,5,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportStats) Reset() {
	*x = ExportStats{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportStats) ProtoMessage() {}

func (x *ExportStats) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportStats.ProtoReflect.Descriptor instead.
func (*ExportStats) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ExportStats) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ExportStats) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ExportStats) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ExportStats) GetWarning() int32 {
	if x != nil {
		return x.Warning
	}
	return 0
}

type ExportMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExportMessageType      `protobuf:"varint,1,opt,name=type,proto3,enum=export.ExportMessageType" json:"type,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	RecordRef     string                 `protobuf:"bytes,6,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMessage) Reset() {
	*x = ExportMessage{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMessage) ProtoMessage() {}

func (x *ExportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMessage.ProtoReflect.Descriptor instead.
func (*ExportMessage) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportMessage) GetType() ExportMessageType {
	if x != nil {
		return x.Type
	}
	return ExportMessageType_EXPORT_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ExportMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ExportMessage) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ExportMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExportMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExportMessage) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

type ExportReportMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	TargetModel   string                 `protobuf:"bytes,2,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportMeta) Reset() {
	*x = ExportReportMeta{}
	mi := &file_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportMeta) ProtoMessage() {}

func (x *ExportReportMeta) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportMeta.ProtoReflect.Descriptor instead.
func (*ExportReportMeta) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{2}
}

func (x *ExportReportMeta) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ExportReportMeta) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

type ExportReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Stats         *ExportStats           `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Messages      []*ExportMessage       `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	ArtifactRef   string                 `protobuf:"bytes,5,opt,name=artifact_ref,json=artifactRef,proto3" json:"artifact_ref,omitempty"`
	Meta          *ExportReportMeta      `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReport) Reset() {
	*x = ExportReport{}
	mi := &file_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReport) ProtoMessage() {}

func (x *ExportReport) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReport.ProtoReflect.Descriptor instead.
func (*ExportReport) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{3}
}

func (x *ExportReport) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ExportReport) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ExportReport) GetStats() *ExportStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ExportReport) GetMessages() []*ExportMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ExportReport) GetArtifactRef() string {
	if x != nil {
		return x.ArtifactRef
	}
	return ""
}

func (x *ExportReport) GetMeta() *ExportReportMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ExportFieldNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Children      []*ExportFieldNode     `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportFieldNode) Reset() {
	*x = ExportFieldNode{}
	mi := &file_export_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportFieldNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFieldNode) ProtoMessage() {}

func (x *ExportFieldNode) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFieldNode.ProtoReflect.Descriptor instead.
func (*ExportFieldNode) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{4}
}

func (x *ExportFieldNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExportFieldNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ExportFieldNode) GetChildren() []*ExportFieldNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type DescribeFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeFieldsRequest) Reset() {
	*x = DescribeFieldsRequest{}
	mi := &file_export_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeFieldsRequest) ProtoMessage() {}

func (x *DescribeFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeFieldsRequest.ProtoReflect.Descriptor instead.
func (*DescribeFieldsRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeFieldsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type DescribeFieldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ExportFieldNode     `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	DefaultFields []string               `protobuf:"bytes,2,rep,name=default_fields,json=defaultFields,proto3" json:"default_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeFieldsResponse) Reset() {
	*x = DescribeFieldsResponse{}
	mi := &file_export_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeFieldsResponse) ProtoMessage() {}

func (x *DescribeFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeFieldsResponse.ProtoReflect.Descriptor instead.
func (*DescribeFieldsResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeFieldsResponse) GetFields() []*ExportFieldNode {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DescribeFieldsResponse) GetDefaultFields() []string {
	if x != nil {
		return x.DefaultFields
	}
	return nil
}

type ExportRunRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Model     string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Mode      ExportMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=export.ExportMode" json:"mode,omitempty"`
	Fields    []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Domain    string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Ids       []string               `protobuf:"bytes,5,rep,name=ids,proto3" json:"ids,omitempty"`
	CompanyId string                 `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// record (default) | terminology
	Profile       string `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	Application   string `protobuf:"bytes,8,opt,name=application,proto3" json:"application,omitempty"`
	Module        string `protobuf:"bytes,9,opt,name=module,proto3" json:"module,omitempty"`
	Lang          string `protobuf:"bytes,10,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRunRequest) Reset() {
	*x = ExportRunRequest{}
	mi := &file_export_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRunRequest) ProtoMessage() {}

func (x *ExportRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRunRequest.ProtoReflect.Descriptor instead.
func (*ExportRunRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{7}
}

func (x *ExportRunRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExportRunRequest) GetMode() ExportMode {
	if x != nil {
		return x.Mode
	}
	return ExportMode_EXPORT_MODE_UNSPECIFIED
}

func (x *ExportRunRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ExportRunRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExportRunRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ExportRunRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ExportRunRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ExportRunRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *ExportRunRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ExportRunRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type ExportRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ExportReport          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	CsvData       []byte                 `protobuf:"bytes,2,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	PoData        []byte                 `protobuf:"bytes,3,opt,name=po_data,json=poData,proto3" json:"po_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRunResponse) Reset() {
	*x = ExportRunResponse{}
	mi := &file_export_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRunResponse) ProtoMessage() {}

func (x *ExportRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRunResponse.ProtoReflect.Descriptor instead.
func (*ExportRunResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{8}
}

func (x *ExportRunResponse) GetReport() *ExportReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ExportRunResponse) GetCsvData() []byte {
	if x != nil {
		return x.CsvData
	}
	return nil
}

func (x *ExportRunResponse) GetPoData() []byte {
	if x != nil {
		return x.PoData
	}
	return nil
}

type ExportRunAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ExportRunRequest      `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRunAsyncRequest) Reset() {
	*x = ExportRunAsyncRequest{}
	mi := &file_export_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRunAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRunAsyncRequest) ProtoMessage() {}

func (x *ExportRunAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRunAsyncRequest.ProtoReflect.Descriptor instead.
func (*ExportRunAsyncRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{9}
}

func (x *ExportRunAsyncRequest) GetRun() *ExportRunRequest {
	if x != nil {
		return x.Run
	}
	return nil
}

type ExportRunAsyncResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DataTransferJobId string                 `protobuf:"bytes,1,opt,name=data_transfer_job_id,json=dataTransferJobId,proto3" json:"data_transfer_job_id,omitempty"`
	TaskJobId         string                 `protobuf:"bytes,2,opt,name=task_job_id,json=taskJobId,proto3" json:"task_job_id,omitempty"`
	Report            *ExportReport          `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportRunAsyncResponse) Reset() {
	*x = ExportRunAsyncResponse{}
	mi := &file_export_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRunAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRunAsyncResponse) ProtoMessage() {}

func (x *ExportRunAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRunAsyncResponse.ProtoReflect.Descriptor instead.
func (*ExportRunAsyncResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{10}
}

func (x *ExportRunAsyncResponse) GetDataTransferJobId() string {
	if x != nil {
		return x.DataTransferJobId
	}
	return ""
}

func (x *ExportRunAsyncResponse) GetTaskJobId() string {
	if x != nil {
		return x.TaskJobId
	}
	return ""
}

func (x *ExportRunAsyncResponse) GetReport() *ExportReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\x12\x06export\"w\n" +
	"\vExportStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\x05R\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\x05R\x05error\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x05R\x04skip\x12\x18\n" +
	"\awarning\x18\x05 \x01(\x05R\awarning\"\xad\x01\n" +
	"\rExportMessage\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.export.ExportMessageTypeR\x04type\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x06 \x01(\tR\trecordRef\"I\n" +
	"\x10ExportReportMeta\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12!\n" +
	"\ftarget_model\x18\x02 \x01(\tR\vtargetModel\"\xf0\x01\n" +
	"\fExportReport\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12)\n" +
	"\x05stats\x18\x03 \x01(\v2\x13.export.ExportStatsR\x05stats\x121\n" +
	"\bmessages\x18\x04 \x03(\v2\x15.export.ExportMessageR\bmessages\x12!\n" +
	"\fartifact_ref\x18\x05 \x01(\tR\vartifactRef\x12,\n" +
	"\x04meta\x18\x06 \x01(\v2\x18.export.ExportReportMetaR\x04meta\"p\n" +
	"\x0fExportFieldNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x123\n" +
	"\bchildren\x18\x03 \x03(\v2\x17.export.ExportFieldNodeR\bchildren\"-\n" +
	"\x15DescribeFieldsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"p\n" +
	"\x16DescribeFieldsResponse\x12/\n" +
	"\x06fields\x18\x01 \x03(\v2\x17.export.ExportFieldNodeR\x06fields\x12%\n" +
	"\x0edefault_fields\x18\x02 \x03(\tR\rdefaultFields\"\x99\x02\n" +
	"\x10ExportRunRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.export.ExportModeR\x04mode\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x10\n" +
	"\x03ids\x18\x05 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"company_id\x18\x06 \x01(\tR\tcompanyId\x12\x18\n" +
	"\aprofile\x18\a \x01(\tR\aprofile\x12 \n" +
	"\vapplication\x18\b \x01(\tR\vapplication\x12\x16\n" +
	"\x06module\x18\t \x01(\tR\x06module\x12\x12\n" +
	"\x04lang\x18\n" +
	" \x01(\tR\x04lang\"u\n" +
	"\x11ExportRunResponse\x12,\n" +
	"\x06report\x18\x01 \x01(\v2\x14.export.ExportReportR\x06report\x12\x19\n" +
	"\bcsv_data\x18\x02 \x01(\fR\acsvData\x12\x17\n" +
	"\apo_data\x18\x03 \x01(\fR\x06poData\"C\n" +
	"\x15ExportRunAsyncRequest\x12*\n" +
	"\x03run\x18\x01 \x01(\v2\x18.export.ExportRunRequestR\x03run\"\x97\x01\n" +
	"\x16ExportRunAsyncResponse\x12/\n" +
	"\x14data_transfer_job_id\x18\x01 \x01(\tR\x11dataTransferJobId\x12\x1e\n" +
	"\vtask_job_id\x18\x02 \x01(\tR\ttaskJobId\x12,\n" +
	"\x06report\x18\x03 \x01(\v2\x14.export.ExportReportR\x06report*Y\n" +
	"\n" +
	"ExportMode\x12\x1b\n" +
	"\x17EXPORT_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EXPORT_MODE_DATA\x10\x01\x12\x18\n" +
	"\x14EXPORT_MODE_TEMPLATE\x10\x02*\x96\x01\n" +
	"\x11ExportMessageType\x12#\n" +
	"\x1fEXPORT_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EXPORT_MESSAGE_TYPE_ERROR\x10\x01\x12\x1f\n" +
	"\x1bEXPORT_MESSAGE_TYPE_WARNING\x10\x02\x12\x1c\n" +
	"\x18EXPORT_MESSAGE_TYPE_SKIP\x10\x032\xa3\x02\n" +
	"\tExportHub\x12O\n" +
	"\x0eDescribeFields\x12\x1d.export.DescribeFieldsRequest\x1a\x1e.export.DescribeFieldsResponse\x12>\n" +
	"\aPreview\x12\x18.export.ExportRunRequest\x1a\x19.export.ExportRunResponse\x12:\n" +
	"\x03Run\x12\x18.export.ExportRunRequest\x1a\x19.export.ExportRunResponse\x12I\n" +
	"\bRunAsync\x12\x1d.export.ExportRunAsyncRequest\x1a\x1e.export.ExportRunAsyncResponseBHZFgithub.com/choysum-dev/choysum/internal/export/proto/exportpb;exportpbb\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_export_proto_goTypes = []any{
	(ExportMode)(0),                // 0: export.ExportMode
	(ExportMessageType)(0),         // 1: export.ExportMessageType
	(*ExportStats)(nil),            // 2: export.ExportStats
	(*ExportMessage)(nil),          // 3: export.ExportMessage
	(*ExportReportMeta)(nil),       // 4: export.ExportReportMeta
	(*ExportReport)(nil),           // 5: export.ExportReport
	(*ExportFieldNode)(nil),        // 6: export.ExportFieldNode
	(*DescribeFieldsRequest)(nil),  // 7: export.DescribeFieldsRequest
	(*DescribeFieldsResponse)(nil), // 8: export.DescribeFieldsResponse
	(*ExportRunRequest)(nil),       // 9: export.ExportRunRequest
	(*ExportRunResponse)(nil),      // 10: export.ExportRunResponse
	(*ExportRunAsyncRequest)(nil),  // 11: export.ExportRunAsyncRequest
	(*ExportRunAsyncResponse)(nil), // 12: export.ExportRunAsyncResponse
}
var file_export_proto_depIdxs = []int32{
	1,  // 0: export.ExportMessage.type:type_name -> export.ExportMessageType
	2,  // 1: export.ExportReport.stats:type_name -> export.ExportStats
	3,  // 2: export.ExportReport.messages:type_name -> export.ExportMessage
	4,  // 3: export.ExportReport.meta:type_name -> export.ExportReportMeta
	6,  // 4: export.ExportFieldNode.children:type_name -> export.ExportFieldNode
	6,  // 5: export.DescribeFieldsResponse.fields:type_name -> export.ExportFieldNode
	0,  // 6: export.ExportRunRequest.mode:type_name -> export.ExportMode
	5,  // 7: export.ExportRunResponse.report:type_name -> export.ExportReport
	9,  // 8: export.ExportRunAsyncRequest.run:type_name -> export.ExportRunRequest
	5,  // 9: export.ExportRunAsyncResponse.report:type_name -> export.ExportReport
	7,  // 10: export.ExportHub.DescribeFields:input_type -> export.DescribeFieldsRequest
	9,  // 11: export.ExportHub.Preview:input_type -> export.ExportRunRequest
	9,  // 12: export.ExportHub.Run:input_type -> export.ExportRunRequest
	11, // 13: export.ExportHub.RunAsync:input_type -> export.ExportRunAsyncRequest
	8,  // 14: export.ExportHub.DescribeFields:output_type -> export.DescribeFieldsResponse
	10, // 15: export.ExportHub.Preview:output_type -> export.ExportRunResponse
	10, // 16: export.ExportHub.Run:output_type -> export.ExportRunResponse
	12, // 17: export.ExportHub.RunAsync:output_type -> export.ExportRunAsyncResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		EnumInfos:         file_export_proto_enumTypes,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
