// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: export.proto

package exportpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExportHub_DescribeFields_FullMethodName = "/export.ExportHub/DescribeFields"
	ExportHub_Preview_FullMethodName        = "/export.ExportHub/Preview"
	ExportHub_Run_FullMethodName            = "/export.ExportHub/Run"
	ExportHub_RunAsync_FullMethodName       = "/export.ExportHub/RunAsync"
)

// ExportHubClient is the client API for ExportHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExportHubClient interface {
	DescribeFields(ctx context.Context, in *DescribeFieldsRequest, opts ...grpc.CallOption) (*DescribeFieldsResponse, error)
	Preview(ctx context.Context, in *ExportRunRequest, opts ...grpc.CallOption) (*ExportRunResponse, error)
	Run(ctx context.Context, in *ExportRunRequest, opts ...grpc.CallOption) (*ExportRunResponse, error)
	RunAsync(ctx context.Context, in *ExportRunAsyncRequest, opts ...grpc.CallOption) (*ExportRunAsyncResponse, error)
}

type exportHubClient struct {
	cc grpc.ClientConnInterface
}

func NewExportHubClient(cc grpc.ClientConnInterface) ExportHubClient {
	return &exportHubClient{cc}
}

func (c *exportHubClient) DescribeFields(ctx context.Context, in *DescribeFieldsRequest, opts ...grpc.CallOption) (*DescribeFieldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeFieldsResponse)
	err := c.cc.Invoke(ctx, ExportHub_DescribeFields_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportHubClient) Preview(ctx context.Context, in *ExportRunRequest, opts ...grpc.CallOption) (*ExportRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRunResponse)
	err := c.cc.Invoke(ctx, ExportHub_Preview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportHubClient) Run(ctx context.Context, in *ExportRunRequest, opts ...grpc.CallOption) (*ExportRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRunResponse)
	err := c.cc.Invoke(ctx, ExportHub_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportHubClient) RunAsync(ctx context.Context, in *ExportRunAsyncRequest, opts ...grpc.CallOption) (*ExportRunAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRunAsyncResponse)
	err := c.cc.Invoke(ctx, ExportHub_RunAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportHubServer is the server API for ExportHub service.
// All implementations must embed UnimplementedExportHubServer
// for forward compatibility.
type ExportHubServer interface {
	DescribeFields(context.Context, *DescribeFieldsRequest) (*DescribeFieldsResponse, error)
	Preview(context.Context, *ExportRunRequest) (*ExportRunResponse, error)
	Run(context.Context, *ExportRunRequest) (*ExportRunResponse, error)
	RunAsync(context.Context, *ExportRunAsyncRequest) (*ExportRunAsyncResponse, error)
	mustEmbedUnimplementedExportHubServer()
}

// UnimplementedExportHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExportHubServer struct{}

func (UnimplementedExportHubServer) DescribeFields(context.Context, *DescribeFieldsRequest) (*DescribeFieldsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeFields not implemented")
}
func (UnimplementedExportHubServer) Preview(context.Context, *ExportRunRequest) (*ExportRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedExportHubServer) Run(context.Context, *ExportRunRequest) (*ExportRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedExportHubServer) RunAsync(context.Context, *ExportRunAsyncRequest) (*ExportRunAsyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAsync not implemented")
}
func (UnimplementedExportHubServer) mustEmbedUnimplementedExportHubServer() {}
func (UnimplementedExportHubServer) testEmbeddedByValue()                   {}

// UnsafeExportHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExportHubServer will
// result in compilation errors.
type UnsafeExportHubServer interface {
	mustEmbedUnimplementedExportHubServer()
}

func RegisterExportHubServer(s grpc.ServiceRegistrar, srv ExportHubServer) {
	// If the following call panics, it indicates UnimplementedExportHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExportHub_ServiceDesc, srv)
}

func _ExportHub_DescribeFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportHubServer).DescribeFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportHub_DescribeFields_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportHubServer).DescribeFields(ctx, req.(*DescribeFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportHub_Preview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportHubServer).Preview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportHub_Preview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportHubServer).Preview(ctx, req.(*ExportRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportHub_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportHubServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportHub_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportHubServer).Run(ctx, req.(*ExportRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportHub_RunAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRunAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportHubServer).RunAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportHub_RunAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportHubServer).RunAsync(ctx, req.(*ExportRunAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExportHub_ServiceDesc is the grpc.ServiceDesc for ExportHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExportHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "export.ExportHub",
	HandlerType: (*ExportHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeFields",
			Handler:    _ExportHub_DescribeFields_Handler,
		},
		{
			MethodName: "Preview",
			Handler:    _ExportHub_Preview_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _ExportHub_Run_Handler,
		},
		{
			MethodName: "RunAsync",
			Handler:    _ExportHub_RunAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "export.proto",
}
