// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: Apache-2.0

export type {
  ModelCtor,
  StandardFields,
  ManyToOneMetadata,
  OneToManyMetadata,
  ManyToManyMetadata,
  BaseFieldOptions,
  FieldStorageHints,
  FieldRelatedOption,
  FieldRelationOption,
  FlatFieldOptions,
  SelectionItem,
  SelectionDeclaration,
  SelectionKind,
  RelationalConditionDeclaration,
  RelationalConditionKind,
  FieldType,
  RelationFieldType,
  ToManyRelationFieldType,
  M2OScalarPath,
  SelectExpressionAtom,
  SelectExpressionValue,
  SelectSubqueryBuilder,
  SelectFieldResolver,
  SelectFieldExistResolver,
  SelectCtx,
  SelectExpressionFn,
  FieldMetadata,
  FieldPathType,
  FieldPath,
  ComputeDep,
  OnchangeTrigger,
  FieldOptions,
} from './field';
export type {
  ConstraintMode,
  ConstraintField,
  ConstraintOptions,
  ConstraintMeta,
  EffectiveConstraintMeta,
  ValidationIssue,
  ConstraintContext,
  ConstraintMethod,
  LegacyConstraintMethod,
  InstanceConstraintMethod,
} from './constraint';
export { ValidationPipelineError } from './constraint';
export type {
  PathDep,
  CollectionPathDep,
  OnchangeHandlerMeta,
  EffectiveOnchangeMeta,
  ComputeHandlerMeta,
  SqlComputeHandlerMeta,
  SearchHandlerMeta,
  InverseHandlerMeta,
  ParsedDep,
  ParentComputeTrigger,
  ModelComputeGraph,
  ModelMetadata,
} from './model';
export type { ValueType, ParamMetadata, ServiceMetadata } from './service';
export type {
  ComputeOperator,
  ComputeSearchDomain,
  ComputeDeps,
  ComputeInverseContext,
  ComputeInverseHandler,
  ComputeSearchContext,
  ComputeSearchHandlerResult,
  ComputeSearchHandler,
} from './compute';
export { MetadataStorage, getEffectiveConstraints, getEffectiveOnchange } from './storage';
