// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: import.proto

package importpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportHub_DescribeImportFields_FullMethodName = "/import.ImportHub/DescribeImportFields"
	ImportHub_ParseHeaders_FullMethodName         = "/import.ImportHub/ParseHeaders"
	ImportHub_Preview_FullMethodName              = "/import.ImportHub/Preview"
	ImportHub_Run_FullMethodName                  = "/import.ImportHub/Run"
	ImportHub_RunAsync_FullMethodName             = "/import.ImportHub/RunAsync"
)

// ImportHubClient is the client API for ImportHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportHubClient interface {
	DescribeImportFields(ctx context.Context, in *DescribeImportFieldsRequest, opts ...grpc.CallOption) (*DescribeImportFieldsResponse, error)
	ParseHeaders(ctx context.Context, in *ParseHeadersRequest, opts ...grpc.CallOption) (*ParseHeadersResponse, error)
	Preview(ctx context.Context, in *ImportRunRequest, opts ...grpc.CallOption) (*ImportRunResponse, error)
	Run(ctx context.Context, in *ImportRunRequest, opts ...grpc.CallOption) (*ImportRunResponse, error)
	RunAsync(ctx context.Context, in *ImportRunAsyncRequest, opts ...grpc.CallOption) (*ImportRunAsyncResponse, error)
}

type importHubClient struct {
	cc grpc.ClientConnInterface
}

func NewImportHubClient(cc grpc.ClientConnInterface) ImportHubClient {
	return &importHubClient{cc}
}

func (c *importHubClient) DescribeImportFields(ctx context.Context, in *DescribeImportFieldsRequest, opts ...grpc.CallOption) (*DescribeImportFieldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeImportFieldsResponse)
	err := c.cc.Invoke(ctx, ImportHub_DescribeImportFields_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importHubClient) ParseHeaders(ctx context.Context, in *ParseHeadersRequest, opts ...grpc.CallOption) (*ParseHeadersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseHeadersResponse)
	err := c.cc.Invoke(ctx, ImportHub_ParseHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importHubClient) Preview(ctx context.Context, in *ImportRunRequest, opts ...grpc.CallOption) (*ImportRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRunResponse)
	err := c.cc.Invoke(ctx, ImportHub_Preview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importHubClient) Run(ctx context.Context, in *ImportRunRequest, opts ...grpc.CallOption) (*ImportRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRunResponse)
	err := c.cc.Invoke(ctx, ImportHub_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importHubClient) RunAsync(ctx context.Context, in *ImportRunAsyncRequest, opts ...grpc.CallOption) (*ImportRunAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRunAsyncResponse)
	err := c.cc.Invoke(ctx, ImportHub_RunAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportHubServer is the server API for ImportHub service.
// All implementations must embed UnimplementedImportHubServer
// for forward compatibility.
type ImportHubServer interface {
	DescribeImportFields(context.Context, *DescribeImportFieldsRequest) (*DescribeImportFieldsResponse, error)
	ParseHeaders(context.Context, *ParseHeadersRequest) (*ParseHeadersResponse, error)
	Preview(context.Context, *ImportRunRequest) (*ImportRunResponse, error)
	Run(context.Context, *ImportRunRequest) (*ImportRunResponse, error)
	RunAsync(context.Context, *ImportRunAsyncRequest) (*ImportRunAsyncResponse, error)
	mustEmbedUnimplementedImportHubServer()
}

// UnimplementedImportHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportHubServer struct{}

func (UnimplementedImportHubServer) DescribeImportFields(context.Context, *DescribeImportFieldsRequest) (*DescribeImportFieldsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeImportFields not implemented")
}
func (UnimplementedImportHubServer) ParseHeaders(context.Context, *ParseHeadersRequest) (*ParseHeadersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseHeaders not implemented")
}
func (UnimplementedImportHubServer) Preview(context.Context, *ImportRunRequest) (*ImportRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedImportHubServer) Run(context.Context, *ImportRunRequest) (*ImportRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedImportHubServer) RunAsync(context.Context, *ImportRunAsyncRequest) (*ImportRunAsyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAsync not implemented")
}
func (UnimplementedImportHubServer) mustEmbedUnimplementedImportHubServer() {}
func (UnimplementedImportHubServer) testEmbeddedByValue()                   {}

// UnsafeImportHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportHubServer will
// result in compilation errors.
type UnsafeImportHubServer interface {
	mustEmbedUnimplementedImportHubServer()
}

func RegisterImportHubServer(s grpc.ServiceRegistrar, srv ImportHubServer) {
	// If the following call panics, it indicates UnimplementedImportHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportHub_ServiceDesc, srv)
}

func _ImportHub_DescribeImportFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeImportFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHubServer).DescribeImportFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHub_DescribeImportFields_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHubServer).DescribeImportFields(ctx, req.(*DescribeImportFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportHub_ParseHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHubServer).ParseHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHub_ParseHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHubServer).ParseHeaders(ctx, req.(*ParseHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportHub_Preview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHubServer).Preview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHub_Preview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHubServer).Preview(ctx, req.(*ImportRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportHub_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHubServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHub_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHubServer).Run(ctx, req.(*ImportRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportHub_RunAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRunAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportHubServer).RunAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportHub_RunAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportHubServer).RunAsync(ctx, req.(*ImportRunAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportHub_ServiceDesc is the grpc.ServiceDesc for ImportHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "import.ImportHub",
	HandlerType: (*ImportHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeImportFields",
			Handler:    _ImportHub_DescribeImportFields_Handler,
		},
		{
			MethodName: "ParseHeaders",
			Handler:    _ImportHub_ParseHeaders_Handler,
		},
		{
			MethodName: "Preview",
			Handler:    _ImportHub_Preview_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _ImportHub_Run_Handler,
		},
		{
			MethodName: "RunAsync",
			Handler:    _ImportHub_RunAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "import.proto",
}
