// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: import.proto

package importpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportPolicy int32

const (
	ImportPolicy_IMPORT_POLICY_UNSPECIFIED ImportPolicy = 0
	ImportPolicy_IMPORT_POLICY_ATOMIC      ImportPolicy = 1
	ImportPolicy_IMPORT_POLICY_STOP_KEEP   ImportPolicy = 2
	ImportPolicy_IMPORT_POLICY_BEST_EFFORT ImportPolicy = 3
)

// Enum value maps for ImportPolicy.
var (
	ImportPolicy_name = map[int32]string{
		0: "IMPORT_POLICY_UNSPECIFIED",
		1: "IMPORT_POLICY_ATOMIC",
		2: "IMPORT_POLICY_STOP_KEEP",
		3: "IMPORT_POLICY_BEST_EFFORT",
	}
	ImportPolicy_value = map[string]int32{
		"IMPORT_POLICY_UNSPECIFIED": 0,
		"IMPORT_POLICY_ATOMIC":      1,
		"IMPORT_POLICY_STOP_KEEP":   2,
		"IMPORT_POLICY_BEST_EFFORT": 3,
	}
)

func (x ImportPolicy) Enum() *ImportPolicy {
	p := new(ImportPolicy)
	*p = x
	return p
}

func (x ImportPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_import_proto_enumTypes[0].Descriptor()
}

func (ImportPolicy) Type() protoreflect.EnumType {
	return &file_import_proto_enumTypes[0]
}

func (x ImportPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportPolicy.Descriptor instead.
func (ImportPolicy) EnumDescriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

type ImportMessageType int32

const (
	ImportMessageType_IMPORT_MESSAGE_TYPE_UNSPECIFIED ImportMessageType = 0
	ImportMessageType_IMPORT_MESSAGE_TYPE_ERROR       ImportMessageType = 1
	ImportMessageType_IMPORT_MESSAGE_TYPE_WARNING     ImportMessageType = 2
	ImportMessageType_IMPORT_MESSAGE_TYPE_SKIP        ImportMessageType = 3
)

// Enum value maps for ImportMessageType.
var (
	ImportMessageType_name = map[int32]string{
		0: "IMPORT_MESSAGE_TYPE_UNSPECIFIED",
		1: "IMPORT_MESSAGE_TYPE_ERROR",
		2: "IMPORT_MESSAGE_TYPE_WARNING",
		3: "IMPORT_MESSAGE_TYPE_SKIP",
	}
	ImportMessageType_value = map[string]int32{
		"IMPORT_MESSAGE_TYPE_UNSPECIFIED": 0,
		"IMPORT_MESSAGE_TYPE_ERROR":       1,
		"IMPORT_MESSAGE_TYPE_WARNING":     2,
		"IMPORT_MESSAGE_TYPE_SKIP":        3,
	}
)

func (x ImportMessageType) Enum() *ImportMessageType {
	p := new(ImportMessageType)
	*p = x
	return p
}

func (x ImportMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_import_proto_enumTypes[1].Descriptor()
}

func (ImportMessageType) Type() protoreflect.EnumType {
	return &file_import_proto_enumTypes[1]
}

func (x ImportMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportMessageType.Descriptor instead.
func (ImportMessageType) EnumDescriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{1}
}

type ImportStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Ok            int32                  `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         int32                  `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Skip          int32                  `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	Warning       int32                  `protobuf:"varint,5,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportStats) Reset() {
	*x = ImportStats{}
	mi := &file_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStats) ProtoMessage() {}

func (x *ImportStats) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStats.ProtoReflect.Descriptor instead.
func (*ImportStats) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

func (x *ImportStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ImportStats) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ImportStats) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ImportStats) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ImportStats) GetWarning() int32 {
	if x != nil {
		return x.Warning
	}
	return 0
}

type ImportMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ImportMessageType      `protobuf:"varint,1,opt,name=type,proto3,enum=import.ImportMessageType" json:"type,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	RecordRef     string                 `protobuf:"bytes,6,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportMessage) Reset() {
	*x = ImportMessage{}
	mi := &file_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMessage) ProtoMessage() {}

func (x *ImportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMessage.ProtoReflect.Descriptor instead.
func (*ImportMessage) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{1}
}

func (x *ImportMessage) GetType() ImportMessageType {
	if x != nil {
		return x.Type
	}
	return ImportMessageType_IMPORT_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ImportMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ImportMessage) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ImportMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImportMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ImportMessage) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

type ImportReportMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	SourceRef     string                 `protobuf:"bytes,2,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	TargetModel   string                 `protobuf:"bytes,3,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportReportMeta) Reset() {
	*x = ImportReportMeta{}
	mi := &file_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReportMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReportMeta) ProtoMessage() {}

func (x *ImportReportMeta) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReportMeta.ProtoReflect.Descriptor instead.
func (*ImportReportMeta) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportReportMeta) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ImportReportMeta) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *ImportReportMeta) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

type ImportReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Policy        ImportPolicy           `protobuf:"varint,2,opt,name=policy,proto3,enum=import.ImportPolicy" json:"policy,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Stats         *ImportStats           `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Messages      []*ImportMessage       `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	ArtifactRef   string                 `protobuf:"bytes,6,opt,name=artifact_ref,json=artifactRef,proto3" json:"artifact_ref,omitempty"`
	Meta          *ImportReportMeta      `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportReport) Reset() {
	*x = ImportReport{}
	mi := &file_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReport) ProtoMessage() {}

func (x *ImportReport) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReport.ProtoReflect.Descriptor instead.
func (*ImportReport) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportReport) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ImportReport) GetPolicy() ImportPolicy {
	if x != nil {
		return x.Policy
	}
	return ImportPolicy_IMPORT_POLICY_UNSPECIFIED
}

func (x *ImportReport) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ImportReport) GetStats() *ImportStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ImportReport) GetMessages() []*ImportMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ImportReport) GetArtifactRef() string {
	if x != nil {
		return x.ArtifactRef
	}
	return ""
}

func (x *ImportReport) GetMeta() *ImportReportMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ParseHeadersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRef     string                 `protobuf:"bytes,1,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseHeadersRequest) Reset() {
	*x = ParseHeadersRequest{}
	mi := &file_import_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseHeadersRequest) ProtoMessage() {}

func (x *ParseHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseHeadersRequest.ProtoReflect.Descriptor instead.
func (*ParseHeadersRequest) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{4}
}

func (x *ParseHeadersRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

type ParseHeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []string               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	Delimiter     string                 `protobuf:"bytes,2,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	HeaderRow     int32                  `protobuf:"varint,3,opt,name=header_row,json=headerRow,proto3" json:"header_row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseHeadersResponse) Reset() {
	*x = ParseHeadersResponse{}
	mi := &file_import_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseHeadersResponse) ProtoMessage() {}

func (x *ParseHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseHeadersResponse.ProtoReflect.Descriptor instead.
func (*ParseHeadersResponse) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{5}
}

func (x *ParseHeadersResponse) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ParseHeadersResponse) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *ParseHeadersResponse) GetHeaderRow() int32 {
	if x != nil {
		return x.HeaderRow
	}
	return 0
}

type ImportRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetModel   string                 `protobuf:"bytes,1,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"`
	SourceRef     string                 `protobuf:"bytes,2,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	ColumnMapping map[string]string      `protobuf:"bytes,3,rep,name=column_mapping,json=columnMapping,proto3" json:"column_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Policy        ImportPolicy           `protobuf:"varint,4,opt,name=policy,proto3,enum=import.ImportPolicy" json:"policy,omitempty"`
	CompanyId     string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRunRequest) Reset() {
	*x = ImportRunRequest{}
	mi := &file_import_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRunRequest) ProtoMessage() {}

func (x *ImportRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRunRequest.ProtoReflect.Descriptor instead.
func (*ImportRunRequest) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{6}
}

func (x *ImportRunRequest) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

func (x *ImportRunRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *ImportRunRequest) GetColumnMapping() map[string]string {
	if x != nil {
		return x.ColumnMapping
	}
	return nil
}

func (x *ImportRunRequest) GetPolicy() ImportPolicy {
	if x != nil {
		return x.Policy
	}
	return ImportPolicy_IMPORT_POLICY_UNSPECIFIED
}

func (x *ImportRunRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ImportRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ImportReport          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRunResponse) Reset() {
	*x = ImportRunResponse{}
	mi := &file_import_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRunResponse) ProtoMessage() {}

func (x *ImportRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRunResponse.ProtoReflect.Descriptor instead.
func (*ImportRunResponse) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{7}
}

func (x *ImportRunResponse) GetReport() *ImportReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ImportRunAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ImportRunRequest      `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRunAsyncRequest) Reset() {
	*x = ImportRunAsyncRequest{}
	mi := &file_import_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRunAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRunAsyncRequest) ProtoMessage() {}

func (x *ImportRunAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRunAsyncRequest.ProtoReflect.Descriptor instead.
func (*ImportRunAsyncRequest) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{8}
}

func (x *ImportRunAsyncRequest) GetRun() *ImportRunRequest {
	if x != nil {
		return x.Run
	}
	return nil
}

type ImportRunAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportJobId   string                 `protobuf:"bytes,1,opt,name=import_job_id,json=importJobId,proto3" json:"import_job_id,omitempty"`
	TaskJobId     string                 `protobuf:"bytes,2,opt,name=task_job_id,json=taskJobId,proto3" json:"task_job_id,omitempty"`
	Report        *ImportReport          `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRunAsyncResponse) Reset() {
	*x = ImportRunAsyncResponse{}
	mi := &file_import_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRunAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRunAsyncResponse) ProtoMessage() {}

func (x *ImportRunAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRunAsyncResponse.ProtoReflect.Descriptor instead.
func (*ImportRunAsyncResponse) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{9}
}

func (x *ImportRunAsyncResponse) GetImportJobId() string {
	if x != nil {
		return x.ImportJobId
	}
	return ""
}

func (x *ImportRunAsyncResponse) GetTaskJobId() string {
	if x != nil {
		return x.TaskJobId
	}
	return ""
}

func (x *ImportRunAsyncResponse) GetReport() *ImportReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_import_proto protoreflect.FileDescriptor

const file_import_proto_rawDesc = "" +
	"\n" +
	"\fimport.proto\x12\x06import\"w\n" +
	"\vImportStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\x05R\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\x05R\x05error\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x05R\x04skip\x12\x18\n" +
	"\awarning\x18\x05 \x01(\x05R\awarning\"\xad\x01\n" +
	"\rImportMessage\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.import.ImportMessageTypeR\x04type\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x06 \x01(\tR\trecordRef\"h\n" +
	"\x10ImportReportMeta\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x02 \x01(\tR\tsourceRef\x12!\n" +
	"\ftarget_model\x18\x03 \x01(\tR\vtargetModel\"\x9e\x02\n" +
	"\fImportReport\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12,\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x14.import.ImportPolicyR\x06policy\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x13.import.ImportStatsR\x05stats\x121\n" +
	"\bmessages\x18\x05 \x03(\v2\x15.import.ImportMessageR\bmessages\x12!\n" +
	"\fartifact_ref\x18\x06 \x01(\tR\vartifactRef\x12,\n" +
	"\x04meta\x18\a \x01(\v2\x18.import.ImportReportMetaR\x04meta\"4\n" +
	"\x13ParseHeadersRequest\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x01 \x01(\tR\tsourceRef\"m\n" +
	"\x14ParseHeadersResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders\x12\x1c\n" +
	"\tdelimiter\x18\x02 \x01(\tR\tdelimiter\x12\x1d\n" +
	"\n" +
	"header_row\x18\x03 \x01(\x05R\theaderRow\"\xb7\x02\n" +
	"\x10ImportRunRequest\x12!\n" +
	"\ftarget_model\x18\x01 \x01(\tR\vtargetModel\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x02 \x01(\tR\tsourceRef\x12R\n" +
	"\x0ecolumn_mapping\x18\x03 \x03(\v2+.import.ImportRunRequest.ColumnMappingEntryR\rcolumnMapping\x12,\n" +
	"\x06policy\x18\x04 \x01(\x0e2\x14.import.ImportPolicyR\x06policy\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x1a@\n" +
	"\x12ColumnMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x11ImportRunResponse\x12,\n" +
	"\x06report\x18\x01 \x01(\v2\x14.import.ImportReportR\x06report\"C\n" +
	"\x15ImportRunAsyncRequest\x12*\n" +
	"\x03run\x18\x01 \x01(\v2\x18.import.ImportRunRequestR\x03run\"\x8a\x01\n" +
	"\x16ImportRunAsyncResponse\x12\"\n" +
	"\rimport_job_id\x18\x01 \x01(\tR\vimportJobId\x12\x1e\n" +
	"\vtask_job_id\x18\x02 \x01(\tR\ttaskJobId\x12,\n" +
	"\x06report\x18\x03 \x01(\v2\x14.import.ImportReportR\x06report*\x83\x01\n" +
	"\fImportPolicy\x12\x1d\n" +
	"\x19IMPORT_POLICY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14IMPORT_POLICY_ATOMIC\x10\x01\x12\x1b\n" +
	"\x17IMPORT_POLICY_STOP_KEEP\x10\x02\x12\x1d\n" +
	"\x19IMPORT_POLICY_BEST_EFFORT\x10\x03*\x96\x01\n" +
	"\x11ImportMessageType\x12#\n" +
	"\x1fIMPORT_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19IMPORT_MESSAGE_TYPE_ERROR\x10\x01\x12\x1f\n" +
	"\x1bIMPORT_MESSAGE_TYPE_WARNING\x10\x02\x12\x1c\n" +
	"\x18IMPORT_MESSAGE_TYPE_SKIP\x10\x032\x9d\x02\n" +
	"\tImportHub\x12I\n" +
	"\fParseHeaders\x12\x1b.import.ParseHeadersRequest\x1a\x1c.import.ParseHeadersResponse\x12>\n" +
	"\aPreview\x12\x18.import.ImportRunRequest\x1a\x19.import.ImportRunResponse\x12:\n" +
	"\x03Run\x12\x18.import.ImportRunRequest\x1a\x19.import.ImportRunResponse\x12I\n" +
	"\bRunAsync\x12\x1d.import.ImportRunAsyncRequest\x1a\x1e.import.ImportRunAsyncResponseBHZFgithub.com/choysum-dev/choysum/internal/import/proto/importpb;importpbb\x06proto3"

var (
	file_import_proto_rawDescOnce sync.Once
	file_import_proto_rawDescData []byte
)

func file_import_proto_rawDescGZIP() []byte {
	file_import_proto_rawDescOnce.Do(func() {
		file_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)))
	})
	return file_import_proto_rawDescData
}

var file_import_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_import_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_import_proto_goTypes = []any{
	(ImportPolicy)(0),              // 0: import.ImportPolicy
	(ImportMessageType)(0),         // 1: import.ImportMessageType
	(*ImportStats)(nil),            // 2: import.ImportStats
	(*ImportMessage)(nil),          // 3: import.ImportMessage
	(*ImportReportMeta)(nil),       // 4: import.ImportReportMeta
	(*ImportReport)(nil),           // 5: import.ImportReport
	(*ParseHeadersRequest)(nil),    // 6: import.ParseHeadersRequest
	(*ParseHeadersResponse)(nil),   // 7: import.ParseHeadersResponse
	(*ImportRunRequest)(nil),       // 8: import.ImportRunRequest
	(*ImportRunResponse)(nil),      // 9: import.ImportRunResponse
	(*ImportRunAsyncRequest)(nil),  // 10: import.ImportRunAsyncRequest
	(*ImportRunAsyncResponse)(nil), // 11: import.ImportRunAsyncResponse
	nil,                            // 12: import.ImportRunRequest.ColumnMappingEntry
}
var file_import_proto_depIdxs = []int32{
	1,  // 0: import.ImportMessage.type:type_name -> import.ImportMessageType
	0,  // 1: import.ImportReport.policy:type_name -> import.ImportPolicy
	2,  // 2: import.ImportReport.stats:type_name -> import.ImportStats
	3,  // 3: import.ImportReport.messages:type_name -> import.ImportMessage
	4,  // 4: import.ImportReport.meta:type_name -> import.ImportReportMeta
	12, // 5: import.ImportRunRequest.column_mapping:type_name -> import.ImportRunRequest.ColumnMappingEntry
	0,  // 6: import.ImportRunRequest.policy:type_name -> import.ImportPolicy
	5,  // 7: import.ImportRunResponse.report:type_name -> import.ImportReport
	8,  // 8: import.ImportRunAsyncRequest.run:type_name -> import.ImportRunRequest
	5,  // 9: import.ImportRunAsyncResponse.report:type_name -> import.ImportReport
	6,  // 10: import.ImportHub.ParseHeaders:input_type -> import.ParseHeadersRequest
	8,  // 11: import.ImportHub.Preview:input_type -> import.ImportRunRequest
	8,  // 12: import.ImportHub.Run:input_type -> import.ImportRunRequest
	10, // 13: import.ImportHub.RunAsync:input_type -> import.ImportRunAsyncRequest
	7,  // 14: import.ImportHub.ParseHeaders:output_type -> import.ParseHeadersResponse
	9,  // 15: import.ImportHub.Preview:output_type -> import.ImportRunResponse
	9,  // 16: import.ImportHub.Run:output_type -> import.ImportRunResponse
	11, // 17: import.ImportHub.RunAsync:output_type -> import.ImportRunAsyncResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_import_proto_init() }
func file_import_proto_init() {
	if File_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_import_proto_goTypes,
		DependencyIndexes: file_import_proto_depIdxs,
		EnumInfos:         file_import_proto_enumTypes,
		MessageInfos:      file_import_proto_msgTypes,
	}.Build()
	File_import_proto = out.File
	file_import_proto_goTypes = nil
	file_import_proto_depIdxs = nil
}
