// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_CheckMethodAccess_Req struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompanyId       string                 `protobuf:"bytes,1,opt,name=companyId,proto3" json:"companyId,omitempty"`
	ServiceFullName string                 `protobuf:"bytes,2,opt,name=serviceFullName,proto3" json:"serviceFullName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User_CheckMethodAccess_Req) Reset() {
	*x = User_CheckMethodAccess_Req{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_CheckMethodAccess_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_CheckMethodAccess_Req) ProtoMessage() {}

func (x *User_CheckMethodAccess_Req) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_CheckMethodAccess_Req.ProtoReflect.Descriptor instead.
func (*User_CheckMethodAccess_Req) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User_CheckMethodAccess_Req) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *User_CheckMethodAccess_Req) GetServiceFullName() string {
	if x != nil {
		return x.ServiceFullName
	}
	return ""
}

type User_CheckMethodAccess_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_CheckMethodAccess_Resp) Reset() {
	*x = User_CheckMethodAccess_Resp{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_CheckMethodAccess_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_CheckMethodAccess_Resp) ProtoMessage() {}

func (x *User_CheckMethodAccess_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_CheckMethodAccess_Resp.ProtoReflect.Descriptor instead.
func (*User_CheckMethodAccess_Resp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *User_CheckMethodAccess_Resp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"d\n" +
	"\x1aUser_CheckMethodAccess_Req\x12\x1c\n" +
	"\tcompanyId\x18\x01 \x01(\tR\tcompanyId\x12(\n" +
	"\x0fserviceFullName\x18\x02 \x01(\tR\x0fserviceFullName\"5\n" +
	"\x1bUser_CheckMethodAccess_Resp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2`\n" +
	"\x04User\x12X\n" +
	"\x11CheckMethodAccess\x12 .auth.User_CheckMethodAccess_Req\x1a!.auth.User_CheckMethodAccess_RespBBZ@github.com/choysum-dev/choysum/pkg/auth/grpcclient/authpb;authpbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_proto_goTypes = []any{
	(*User_CheckMethodAccess_Req)(nil),  // 0: auth.User_CheckMethodAccess_Req
	(*User_CheckMethodAccess_Resp)(nil), // 1: auth.User_CheckMethodAccess_Resp
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.User.CheckMethodAccess:input_type -> auth.User_CheckMethodAccess_Req
	1, // 1: auth.User.CheckMethodAccess:output_type -> auth.User_CheckMethodAccess_Resp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
