// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

//go:build ignore

// gen_vue_version.go writes vue_version.go from modules/web/package.json
// (exact "vue" peer/dependency) and keeps internal/bootstrap/web in sync.
//
// SSOT for the Vue runtime pin: modules/web/package.json.
// Upgrade: edit that exact "vue" pin, then:
//
//	go generate ./pkg/jsengine/scripts/choysummount/...
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/choysum-dev/choysum/pkg/jsengine/scripts/choysummount"
)

type packageJSON struct {
	Dependencies     map[string]string `json:"dependencies"`
	PeerDependencies map[string]string `json:"peerDependencies"`
}

func main() {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fail("cannot locate generator source")
	}
	pkgDir := filepath.Dir(thisFile)
	repoRoot := findRepoRoot(pkgDir)
	webPkg := filepath.Join(repoRoot, "modules", "web", "package.json")
	ver, err := exactVueFromPackageJSON(webPkg)
	if err != nil {
		fail("modules/web: %v", err)
	}

	out := filepath.Join(pkgDir, "vue_version.go")
	content := fmt.Sprintf(`// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by go generate ./pkg/jsengine/scripts/choysummount/...; DO NOT EDIT.
// Source: modules/web/package.json exact "vue" peer/dependency.

package choysummount

// VuePackageVersion is the fallback Vue runtime pin (generated from
// modules/web/package.json). Prefer ExactPinsFromPackageJSON at build time;
// this const is for FE/unit hosts when that file is absent.
const VuePackageVersion = %q
`, ver)
	if err := os.WriteFile(out, []byte(content), 0o644); err != nil {
		fail("write %s: %v", out, err)
	}
	fmt.Printf("wrote %s (VuePackageVersion=%s)\n", out, ver)

	bootPkg := filepath.Join(repoRoot, "internal", "bootstrap", "web", "package.json")
	if err := syncBootstrapVue(bootPkg, ver); err != nil {
		fail("bootstrap web: %v", err)
	}
}

func findRepoRoot(start string) string {
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fail("go.mod not found above %s", start)
		}
		dir = parent
	}
}

func exactVueFromPackageJSON(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	var pkg packageJSON
	if err := json.Unmarshal(data, &pkg); err != nil {
		return "", fmt.Errorf("parse %s: %w", path, err)
	}
	dep := normalizeVue(pkg.Dependencies["vue"])
	peer := normalizeVue(pkg.PeerDependencies["vue"])
	if dep != "" && peer != "" && dep != peer {
		return "", fmt.Errorf("%s conflicting vue: dependencies=%q peerDependencies=%q", path, dep, peer)
	}
	ver := dep
	if ver == "" {
		ver = peer
	}
	if ver == "" {
		return "", fmt.Errorf("%s missing exact vue pin", path)
	}
	if !choysummount.IsExactVuePin(ver) {
		return "", fmt.Errorf("%s vue must be exact major.minor.patch (got %q)", path, ver)
	}
	return ver, nil
}

func normalizeVue(raw string) string {
	return strings.TrimPrefix(strings.TrimSpace(raw), "v")
}

func syncBootstrapVue(path, ver string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var pkg packageJSON
	if err := json.Unmarshal(data, &pkg); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}
	if pkg.Dependencies == nil {
		pkg.Dependencies = map[string]string{}
	}
	cur := normalizeVue(pkg.Dependencies["vue"])
	if cur == ver {
		fmt.Printf("bootstrap web vue already %s\n", ver)
		return nil
	}
	// Preserve key order / formatting by rewriting only the dependencies.vue
	// string value when present as an exact JSON string.
	old := []byte(`"vue": "` + cur + `"`)
	neu := []byte(`"vue": "` + ver + `"`)
	if cur == "" || !bytes.Contains(data, old) {
		return fmt.Errorf("%s: cannot sync vue %q → %q (edit dependencies.vue manually)", path, cur, ver)
	}
	if n := bytes.Count(data, old); n != 1 {
		return fmt.Errorf("%s: expected exactly one %s, found %d", path, old, n)
	}
	updated := bytes.ReplaceAll(data, old, neu)
	var check packageJSON
	if err := json.Unmarshal(updated, &check); err != nil {
		return fmt.Errorf("%s: refusing to write invalid JSON: %w", path, err)
	}
	if normalizeVue(check.Dependencies["vue"]) != ver {
		return fmt.Errorf("%s: sync did not set dependencies.vue to %q (got %q)", path, ver, check.Dependencies["vue"])
	}
	if err := os.WriteFile(path, updated, 0o644); err != nil {
		return err
	}
	fmt.Printf("synced %s vue %s → %s\n", path, cur, ver)
	return nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_vue_version: "+format+"\n", args...)
	os.Exit(1)
}
