// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by go generate ./pkg/jsengine/scripts/choysummount/...; DO NOT EDIT.
// Source: modules/web/package.json exact "vue" peer/dependency.

package choysummount

// VuePackageVersion is the fallback Vue runtime pin (generated from
// modules/web/package.json). Prefer ExactPinsFromPackageJSON at build time;
// this const is for FE/unit hosts when that file is absent.
const VuePackageVersion = "3.5.38"
