// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package extract

import (
	"bytes"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
)

// PotEntry is one GNU gettext pot message with required msgctxt (Scope).
type PotEntry struct {
	Msgctxt    string
	Msgid      string
	Kind       string
	References []string // path:line comments for #:
}

// WritePot writes a GNU gettext-compatible .pot file.
// Every entry must have msgctxt (D12c).
func WritePot(w io.Writer, moduleName string, entries []PotEntry) error {
	var buf bytes.Buffer
	buf.WriteString("# Terminology catalog for module " + moduleName + ".\n")
	buf.WriteString("# Generated by choysum i18n extract. DO NOT EDIT BY HAND for msgid/msgctxt.\n")
	buf.WriteString("# Template regex for Vue <template> is temporary (S1-MVP); S1+ will use template AST.\n")
	buf.WriteString("#\n")
	buf.WriteString("msgid \"\"\n")
	buf.WriteString("msgstr \"\"\n")
	buf.WriteString("\"Content-Type: text/plain; charset=UTF-8\\n\"\n")
	buf.WriteString("\"Content-Transfer-Encoding: 8bit\\n\"\n")
	buf.WriteString("\n")

	sorted := append([]PotEntry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Msgctxt != sorted[j].Msgctxt {
			return sorted[i].Msgctxt < sorted[j].Msgctxt
		}
		if sorted[i].Msgid != sorted[j].Msgid {
			return sorted[i].Msgid < sorted[j].Msgid
		}
		return sorted[i].Kind < sorted[j].Kind
	})

	for _, entry := range sorted {
		if strings.TrimSpace(entry.Msgctxt) == "" {
			return fmt.Errorf("pot entry missing msgctxt for msgid %q", entry.Msgid)
		}
		refs := uniqueSorted(entry.References)
		for _, ref := range refs {
			buf.WriteString("#: ")
			buf.WriteString(ref)
			buf.WriteByte('\n')
		}
		if entry.Kind != "" && entry.Kind != KindLiteral {
			buf.WriteString("#. kind: ")
			buf.WriteString(entry.Kind)
			buf.WriteByte('\n')
		}
		buf.WriteString("msgctxt ")
		buf.WriteString(quotePoString(entry.Msgctxt))
		buf.WriteByte('\n')
		buf.WriteString("msgid ")
		buf.WriteString(quotePoString(entry.Msgid))
		buf.WriteByte('\n')
		buf.WriteString("msgstr \"\"\n")
		buf.WriteByte('\n')
	}

	_, err := io.Copy(w, &buf)
	return err
}

func quotePoString(s string) string {
	return strconv.Quote(s)
}

func uniqueSorted(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, v := range values {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		if _, ok := seen[v]; ok {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

// DedupeOccurrences merges occurrences into pot entries keyed by (scope, src, kind).
func DedupeOccurrences(terms []TermOccurrence) []PotEntry {
	type key struct {
		scope, src, kind string
	}
	merged := map[key]*PotEntry{}
	order := make([]key, 0)
	for _, term := range terms {
		k := key{scope: term.Scope, src: term.Src, kind: term.Kind}
		if k.kind == "" {
			k.kind = KindLiteral
		}
		entry, ok := merged[k]
		if !ok {
			entry = &PotEntry{
				Msgctxt: k.scope,
				Msgid:   k.src,
				Kind:    k.kind,
			}
			merged[k] = entry
			order = append(order, k)
		}
		if term.SourcePath != "" {
			ref := term.SourcePath
			if term.Line > 0 {
				ref = fmt.Sprintf("%s:%d", term.SourcePath, term.Line)
			}
			entry.References = append(entry.References, ref)
		}
	}
	out := make([]PotEntry, 0, len(order))
	for _, k := range order {
		out = append(out, *merged[k])
	}
	return out
}
