// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package model

import (
	"time"

	"github.com/choysum-dev/choysum/pkg/meta"
)

// LockLease provides a DB-agnostic mutual exclusion primitive.
// It is intentionally simple to support Postgres/MySQL/SQLite via GORM.
//
// Resource should be globally unique (uniqueIndex) to represent one lock.
// ExpiresAt enables lease semantics to recover from crashed owners.
// OwnerId is an opaque identifier generated by the caller.
//
// NOTE: Acquire/Renew/Release logic lives in internal/state/lease.
type LockLease struct {
	meta.BaseModel
	Resource  string `gorm:"uniqueIndex"`
	OwnerId   string
	ExpiresAt time.Time `gorm:"index"`
}

func (l *LockLease) TableName() string {
	return "meta_lock_lease"
}
