// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: Apache-2.0

// @generated by choysum gots with parameter "target=ts"

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';

// File descriptor for internal/tip/proto/tip.proto
export const file_internal_tip_proto_tip: GenFile = fileDesc('ChxpbnRlcm5hbC90aXAvcHJvdG8vdGlwLnByb3RvEgN0aXAitgEKA1RpcBIUCgV0b3BpYxgBIAEoCVIFdG9waWMSHAoKYXRfdW5peF9tcxgCIAEoA1IIYXRVbml4TXMSFgoGc291cmNlGAMgASgJUgZzb3VyY2USFAoFbW9kZWwYBCABKAlSBW1vZGVsEhUKBnJlc19pZBgFIAEoCVIFcmVzSWQSHQoKbWVzc2FnZV9pZBgGIAEoCVIJbWVzc2FnZUlkEhcKB3VzZXJfaWQYByABKAlSBnVzZXJJZCJBChJTdWJzY3JpYmVUaHJlYWRSZXESFAoFbW9kZWwYASABKAlSBW1vZGVsEhUKBnJlc19pZBgCIAEoCVIFcmVzSWQiGwoZU3Vic2NyaWJlTm90aWZpY2F0aW9uc1JlcSItChRTdWJzY3JpYmVNb2R1bGVPcFJlcRIVCgZqb2JfaWQYASABKAlSBWpvYklkMsIBCgZUaXBIdWISNgoPU3Vic2NyaWJlVGhyZWFkEhcudGlwLlN1YnNjcmliZVRocmVhZFJlcRoILnRpcC5UaXAwARJEChZTdWJzY3JpYmVOb3RpZmljYXRpb25zEh4udGlwLlN1YnNjcmliZU5vdGlmaWNhdGlvbnNSZXEaCC50aXAuVGlwMAESOgoRU3Vic2NyaWJlTW9kdWxlT3ASGS50aXAuU3Vic2NyaWJlTW9kdWxlT3BSZXEaCC50aXAuVGlwMAFCP1o9Z2l0aHViLmNvbS9jaG95c3VtLWRldi9jaG95c3VtL2ludGVybmFsL3RpcC9wcm90by90aXBwYjt0aXBwYmIGcHJvdG8z');

// Message Tip
export type Tip = Message<'tip.Tip'> & {
  topic: string;
  atUnixMs: bigint;
  source: string;
  model: string;
  resId: string;
  messageId: string;
  userId: string;
};

export const TipSchema: GenMessage<Tip> = messageDesc(file_internal_tip_proto_tip, 0);

// Message SubscribeThreadReq
export type SubscribeThreadReq = Message<'tip.SubscribeThreadReq'> & {
  model: string;
  resId: string;
};

export const SubscribeThreadReqSchema: GenMessage<SubscribeThreadReq> = messageDesc(file_internal_tip_proto_tip, 1);

// Message SubscribeNotificationsReq
export type SubscribeNotificationsReq = Message<'tip.SubscribeNotificationsReq'> & {
};

export const SubscribeNotificationsReqSchema: GenMessage<SubscribeNotificationsReq> = messageDesc(file_internal_tip_proto_tip, 2);

// Message SubscribeModuleOpReq
export type SubscribeModuleOpReq = Message<'tip.SubscribeModuleOpReq'> & {
  jobId: string;
};

export const SubscribeModuleOpReqSchema: GenMessage<SubscribeModuleOpReq> = messageDesc(file_internal_tip_proto_tip, 3);

// Service TipHub
export const TipHub = serviceDesc(file_internal_tip_proto_tip, 0);

