// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: Apache-2.0

// @generated by choysum gots with parameter "target=ts"

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';

// File descriptor for internal/tip/proto/tip.proto
export const file_internal_tip_proto_tip: GenFile = fileDesc('ChxpbnRlcm5hbC90aXAvcHJvdG8vdGlwLnByb3RvEg5jaG95c3VtLnRpcC52MSK2AQoDVGlwEhQKBXRvcGljGAEgASgJUgV0b3BpYxIcCgphdF91bml4X21zGAIgASgDUghhdFVuaXhNcxIWCgZzb3VyY2UYAyABKAlSBnNvdXJjZRIUCgVtb2RlbBgEIAEoCVIFbW9kZWwSFQoGcmVzX2lkGAUgASgJUgVyZXNJZBIdCgptZXNzYWdlX2lkGAYgASgJUgltZXNzYWdlSWQSFwoHdXNlcl9pZBgHIAEoCVIGdXNlcklkIkEKElN1YnNjcmliZVRocmVhZFJlcRIUCgVtb2RlbBgBIAEoCVIFbW9kZWwSFQoGcmVzX2lkGAIgASgJUgVyZXNJZCIbChlTdWJzY3JpYmVOb3RpZmljYXRpb25zUmVxMrIBCgZUaXBIdWISTAoPU3Vic2NyaWJlVGhyZWFkEiIuY2hveXN1bS50aXAudjEuU3Vic2NyaWJlVGhyZWFkUmVxGhMuY2hveXN1bS50aXAudjEuVGlwMAESWgoWU3Vic2NyaWJlTm90aWZpY2F0aW9ucxIpLmNob3lzdW0udGlwLnYxLlN1YnNjcmliZU5vdGlmaWNhdGlvbnNSZXEaEy5jaG95c3VtLnRpcC52MS5UaXAwAUI/Wj1naXRodWIuY29tL2Nob3lzdW0tZGV2L2Nob3lzdW0vaW50ZXJuYWwvdGlwL3Byb3RvL3RpcHBiO3RpcHBiYgZwcm90bzM=');

// Message Tip
export type Tip = Message<'choysum.tip.v1.Tip'> & {
  topic: string;
  atUnixMs: bigint;
  source: string;
  model: string;
  resId: string;
  messageId: string;
  userId: string;
};

export const TipSchema: GenMessage<Tip> = messageDesc(file_internal_tip_proto_tip, 0);

// Message SubscribeThreadReq
export type SubscribeThreadReq = Message<'choysum.tip.v1.SubscribeThreadReq'> & {
  model: string;
  resId: string;
};

export const SubscribeThreadReqSchema: GenMessage<SubscribeThreadReq> = messageDesc(file_internal_tip_proto_tip, 1);

// Message SubscribeNotificationsReq
export type SubscribeNotificationsReq = Message<'choysum.tip.v1.SubscribeNotificationsReq'> & {
};

export const SubscribeNotificationsReqSchema: GenMessage<SubscribeNotificationsReq> = messageDesc(file_internal_tip_proto_tip, 2);

// Service TipHub
export const TipHub = serviceDesc(file_internal_tip_proto_tip, 0);

