// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: Apache-2.0

// @generated by choysum gots with parameter "target=ts"

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';

// File descriptor for internal/realtime/proto/tip.proto
export const file_internal_realtime_proto_tip: GenFile = fileDesc('CiFpbnRlcm5hbC9yZWFsdGltZS9wcm90by90aXAucHJvdG8SE2Nob3lzdW0ucmVhbHRpbWUudjEitgEKA1RpcBIUCgV0b3BpYxgBIAEoCVIFdG9waWMSHAoKYXRfdW5peF9tcxgCIAEoA1IIYXRVbml4TXMSFgoGc291cmNlGAMgASgJUgZzb3VyY2USFAoFbW9kZWwYBCABKAlSBW1vZGVsEhUKBnJlc19pZBgFIAEoCVIFcmVzSWQSHQoKbWVzc2FnZV9pZBgGIAEoCVIJbWVzc2FnZUlkEhcKB3VzZXJfaWQYByABKAlSBnVzZXJJZCJBChJTdWJzY3JpYmVUaHJlYWRSZXESFAoFbW9kZWwYASABKAlSBW1vZGVsEhUKBnJlc19pZBgCIAEoCVIFcmVzSWQiGwoZU3Vic2NyaWJlTm90aWZpY2F0aW9uc1JlcTLGAQoGVGlwSHViElYKD1N1YnNjcmliZVRocmVhZBInLmNob3lzdW0ucmVhbHRpbWUudjEuU3Vic2NyaWJlVGhyZWFkUmVxGhguY2hveXN1bS5yZWFsdGltZS52MS5UaXAwARJkChZTdWJzY3JpYmVOb3RpZmljYXRpb25zEi4uY2hveXN1bS5yZWFsdGltZS52MS5TdWJzY3JpYmVOb3RpZmljYXRpb25zUmVxGhguY2hveXN1bS5yZWFsdGltZS52MS5UaXAwAUJEWkJnaXRodWIuY29tL2Nob3lzdW0tZGV2L2Nob3lzdW0vaW50ZXJuYWwvcmVhbHRpbWUvcHJvdG8vdGlwcGI7dGlwcGJiBnByb3RvMw==');

// Message Tip
export type Tip = Message<'choysum.realtime.v1.Tip'> & {
  topic: string;
  atUnixMs: bigint;
  source: string;
  model: string;
  resId: string;
  messageId: string;
  userId: string;
};

export const TipSchema: GenMessage<Tip> = messageDesc(file_internal_realtime_proto_tip, 0);

// Message SubscribeThreadReq
export type SubscribeThreadReq = Message<'choysum.realtime.v1.SubscribeThreadReq'> & {
  model: string;
  resId: string;
};

export const SubscribeThreadReqSchema: GenMessage<SubscribeThreadReq> = messageDesc(file_internal_realtime_proto_tip, 1);

// Message SubscribeNotificationsReq
export type SubscribeNotificationsReq = Message<'choysum.realtime.v1.SubscribeNotificationsReq'> & {
};

export const SubscribeNotificationsReqSchema: GenMessage<SubscribeNotificationsReq> = messageDesc(file_internal_realtime_proto_tip, 2);

// Service TipHub
export const TipHub = serviceDesc(file_internal_realtime_proto_tip, 0);

