// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: Apache-2.0

export { db, Repository } from './repository';
export { RepositoryFactory } from './repository_factory';

export { DeleteResult, UpdateResult, InsertResult, ExpressionBuilder, ExpressionWrapper, SelectQueryBuilder, Compilable, SimplifyResult } from './types';
export type {
  SelectResult,
  Entity,
  FilteredQueryProperties,
  FilteredInputProperties,
  Selectable,
  Queryable,
  IdRelationItem,
  ModelRelationItem,
  RelationItem,
  RelationOperations,
  Insertable,
  Updateable,
  DeepRelationSelection,
  FieldSelection,
  Operator,
  BaseCondition,
  BaseQueryCondition,
  NestedPath,
  QueryCondition,
  OrderBy,
  SoftDeleteMode,
  SoftDeleteOptions,
  SearchOptions,
  CountOptions,
  UpdateOptions,
  DeleteOptions,
  TemporalGranularity,
  AggregateFunction,
  QueryPath,
  QueryablePath,
  GroupBySpec,
  FieldAggregation,
  RepoReadGroupOptions,
  RepoReadGroupRow,
  RepoReadTotalsOptions,
  RepoReadTotalsRow,
  RepoReadGroupCountOptions,
  ReadGroupShape,
  ReadGroupOptions,
  ReadGroupCountOptions,
  GroupRow,
  ReadGroupResult,
  RecordRuleOp,
  ConditionExpr,
  ConditionEnvelope,
} from './types';

export {
  createRepositoryConditionQueryDeps,
  createRepositoryReadConditionDeps,
  createRepositoryReadOrderDeps,
  createRepositoryReadQueryFacadeDeps,
  createRepositorySearchFacadeDeps,
  createRepositoryReadAggregateDeps,
  createRepositoryReadAggregateFacadeDeps,
  executeRepositorySearch,
  executeRepositoryReadGroup,
  executeRepositoryReadTotals,
  executeRepositoryReadGroupCount,
  buildRepositoryReadAggregateGroupExprs,
  buildRepositoryReadAggregateSelections,
  buildRepositoryReadAggregateTotalSelections,
  applyRepositoryReadAggregateCondition,
  resolveRepositoryReadAggregateKnownAliases,
  normalizeRepositoryAggregateDecimals,
  normalizeGroupBySpec,
  normalizeGroupBySpecs,
  normalizeFieldAggregation,
  rebuildGroupSpec,
  rebuildCompositeGroupSpec,
  rebuildAggFields,
  coerceToBucketStart,
  nextBucket,
  enumerateBuckets,
} from './read';
export type { NormalizedGroupSpec, NormalizedCompositeGroupSpec, NormalizedAgg } from './read';

export {
  convertCondition,
  isEmptyCondition,
  andAll,
  toRepoCondition,
  buildContainsExpression,
  repositorySoftDeleteEnabled,
  isEmptyRepositoryCondition,
  andRepositoryConditions,
  applyRepositorySoftDeleteLayer,
  applyRepositoryDefaultLayers,
  locateRepositoryIdsForCondition,
  countRepositoryConditionMatches,
  convertRepositoryHavingCondition,
  normalizeOrderBy,
  computeFallbackOrder,
  resolveEffectiveOrder,
  applyOrderByToQuery,
  makeSelectCtx,
  getStringHelpers,
} from './query';
export type { RepositoryVisibilityLayerDeps, RepositoryDefaultLayerDeps, RepositoryOrderSpec, DbLike } from './query';
