// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tip.proto

package tippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tip is a best-effort lean signal. Authoritative state lives in tables;
// clients re-read via unary RPCs after receiving a tip.
type Tip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,2,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	ResId         string                 `protobuf:"bytes,5,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tip) Reset() {
	*x = Tip{}
	mi := &file_tip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tip) ProtoMessage() {}

func (x *Tip) ProtoReflect() protoreflect.Message {
	mi := &file_tip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tip.ProtoReflect.Descriptor instead.
func (*Tip) Descriptor() ([]byte, []int) {
	return file_tip_proto_rawDescGZIP(), []int{0}
}

func (x *Tip) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Tip) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *Tip) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Tip) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Tip) GetResId() string {
	if x != nil {
		return x.ResId
	}
	return ""
}

func (x *Tip) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Tip) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscribeThreadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ResId         string                 `protobuf:"bytes,2,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeThreadReq) Reset() {
	*x = SubscribeThreadReq{}
	mi := &file_tip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeThreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeThreadReq) ProtoMessage() {}

func (x *SubscribeThreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_tip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeThreadReq.ProtoReflect.Descriptor instead.
func (*SubscribeThreadReq) Descriptor() ([]byte, []int) {
	return file_tip_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeThreadReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SubscribeThreadReq) GetResId() string {
	if x != nil {
		return x.ResId
	}
	return ""
}

type SubscribeNotificationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeNotificationsReq) Reset() {
	*x = SubscribeNotificationsReq{}
	mi := &file_tip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeNotificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNotificationsReq) ProtoMessage() {}

func (x *SubscribeNotificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_tip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNotificationsReq.ProtoReflect.Descriptor instead.
func (*SubscribeNotificationsReq) Descriptor() ([]byte, []int) {
	return file_tip_proto_rawDescGZIP(), []int{2}
}

var File_tip_proto protoreflect.FileDescriptor

const file_tip_proto_rawDesc = "" +
	"\n" +
	"\ttip.proto\x12\x0echoysum.tip.v1\"\xb6\x01\n" +
	"\x03Tip\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x02 \x01(\x03R\batUnixMs\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x15\n" +
	"\x06res_id\x18\x05 \x01(\tR\x05resId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"A\n" +
	"\x12SubscribeThreadReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x15\n" +
	"\x06res_id\x18\x02 \x01(\tR\x05resId\"\x1b\n" +
	"\x19SubscribeNotificationsReq2\xb2\x01\n" +
	"\x06TipHub\x12L\n" +
	"\x0fSubscribeThread\x12\".choysum.tip.v1.SubscribeThreadReq\x1a\x13.choysum.tip.v1.Tip0\x01\x12Z\n" +
	"\x16SubscribeNotifications\x12).choysum.tip.v1.SubscribeNotificationsReq\x1a\x13.choysum.tip.v1.Tip0\x01B?Z=github.com/choysum-dev/choysum/internal/tip/proto/tippb;tippbb\x06proto3"

var (
	file_tip_proto_rawDescOnce sync.Once
	file_tip_proto_rawDescData []byte
)

func file_tip_proto_rawDescGZIP() []byte {
	file_tip_proto_rawDescOnce.Do(func() {
		file_tip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tip_proto_rawDesc), len(file_tip_proto_rawDesc)))
	})
	return file_tip_proto_rawDescData
}

var file_tip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tip_proto_goTypes = []any{
	(*Tip)(nil),                       // 0: choysum.tip.v1.Tip
	(*SubscribeThreadReq)(nil),        // 1: choysum.tip.v1.SubscribeThreadReq
	(*SubscribeNotificationsReq)(nil), // 2: choysum.tip.v1.SubscribeNotificationsReq
}
var file_tip_proto_depIdxs = []int32{
	1, // 0: choysum.tip.v1.TipHub.SubscribeThread:input_type -> choysum.tip.v1.SubscribeThreadReq
	2, // 1: choysum.tip.v1.TipHub.SubscribeNotifications:input_type -> choysum.tip.v1.SubscribeNotificationsReq
	0, // 2: choysum.tip.v1.TipHub.SubscribeThread:output_type -> choysum.tip.v1.Tip
	0, // 3: choysum.tip.v1.TipHub.SubscribeNotifications:output_type -> choysum.tip.v1.Tip
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tip_proto_init() }
func file_tip_proto_init() {
	if File_tip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tip_proto_rawDesc), len(file_tip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tip_proto_goTypes,
		DependencyIndexes: file_tip_proto_depIdxs,
		MessageInfos:      file_tip_proto_msgTypes,
	}.Build()
	File_tip_proto = out.File
	file_tip_proto_goTypes = nil
	file_tip_proto_depIdxs = nil
}
