// SPDX-FileCopyrightText: 2026-present Brian Wang <wangbuke@gmail.com>
// SPDX-License-Identifier: LGPL-3.0-or-later

package e2e

// e2eGlobalResolveHookSource is written to each e2e runDir and loaded via
// NODE_OPTIONS=--import so Playwright resolves bare npm packages from the
// global node_modules root without temporary local symlinks.
const e2eGlobalResolveHookSource = `// Auto-generated by choysum test e2e (do not edit).
import { registerHooks } from 'node:module';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const globalRoot = String(process.env.CHOYSUM_E2E_GLOBAL_NODE_MODULES || '').trim();
if (!globalRoot) {
  throw new Error('CHOYSUM_E2E_GLOBAL_NODE_MODULES is required for e2e global npm resolve');
}

// Resolve as if the importer lived next to the global node_modules directory
// (so Node walks into <globalRoot>/<pkg>, including scoped packages).
const parentURL = pathToFileURL(path.join(globalRoot, '..', '.choysum-e2e-resolve-anchor')).href;

function isBareSpecifier(specifier) {
  if (!specifier || typeof specifier !== 'string') return false;
  if (specifier.startsWith('node:')) return false;
  if (specifier.startsWith('file:')) return false;
  if (specifier.startsWith('data:')) return false;
  if (specifier.startsWith('./') || specifier.startsWith('../')) return false;
  if (path.isAbsolute(specifier)) return false;
  return true;
}

function isUnderGlobal(parentURLValue) {
  if (!parentURLValue || typeof parentURLValue !== 'string') return false;
  if (!parentURLValue.startsWith('file:')) return false;
  try {
    const parentPath = fileURLToPath(parentURLValue);
    const rel = path.relative(globalRoot, parentPath);
    return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
  } catch {
    return false;
  }
}

registerHooks({
  resolve(specifier, context, nextResolve) {
    if (!isBareSpecifier(specifier)) {
      return nextResolve(specifier, context);
    }
    // Importers already inside the global npm tree keep default resolution so
    // nested deps (e.g. playwright under @playwright/test/node_modules) work.
    if (isUnderGlobal(context.parentURL)) {
      return nextResolve(specifier, context);
    }
    return nextResolve(specifier, { ...context, parentURL });
  },
});
`
